module;

#include <vector>
#include <string>

export module Games:Strings;

using namespace std;
using namespace std::string_literals;

// Touhou 06
export const vector<string> th06_musicNames = {
    "A Dream More Scarlet than Red"s,
    "A Soul as Scarlet as a Ground Cherry"s,
    "Apparitions Stalk the Night"s,
    "Lunate Elf"s,
    "Tomboyish Girl in Love"s,
    "Shanghai Scarlet Teahouse ~ Chinese Tea"s,
    "Shanghai Alice of Meiji 17"s,
    "Voile, the Magic Library"s,
    "Locked Girl ~ The Girl's Sealed Room"s,
    "The Maid and the Pocket Watch of Blood"s,
    "Lunar Clock ~ Luna Dial"s,
    "The Young Descendant of Tepes"s,
    "Septette for a Dead Princess"s,
    "The Centennial Festival for Magical Girls"s,
    "U.N. Owen was Her?"s,
    "An Eternity More Transient than Scarlet"s,
    "Scarlet Tower ~ Eastern Dream..."s,
};

// Touhou 07
export const vector<string> th07_musicNames = {
    "Ghostly Dream ~ Snow or Cherry Petal"s,
    "Paradise ~ Deep Mountain"s,
    "Crystallized Silver"s,
    "The Fantastic Tales from Tono"s,
    "Diao Ye Zong (withered leaf)"s,
    "The Doll Maker of Bucuresti"s,
    "Doll Judgement ~ The Girl Who Played with People's Shapes"s,
    "The Capital City of Flowers in the Sky"s,
    "Phantom Band ~ Phantom Ensemble"s,
    "Eastern Ghostly Dream ~ Ancient Temple"s,
    "Hiroari Shoots a Strange Bird ~ Till When?"s,
    "Ultimate Truth"s,
    "Bloom Nobly, Ink-Black Cherry Blossom ~ Border of Life"s,
    "Border of Life"s,
    "Spiritual Domination"s,
    "A Maiden's Illusionary Funeral ~ Necro-Fantasy"s,
    "Spiritual Domination ~ Who done it!"s,
    "Necrofantasia"s,
    "Dream of a Spring Breeze"s,
    "Sakura, Sakura ~ Japanize Dream..."s,
};

// Touhou 08
export const vector<string> th08_musicNames = {
    "Eternal Night Vignette ~ Eastern Night"s,
    "Illusionary Night ~ Ghostly Eyes"s,
    "Stirring an Autumn Moon ~ Mooned Insect"s,
    "Song of the Night Sparrow ~ Night Bird"s,
    "Deaf to All but the Song"s,
    "Nostalgic Blood of the East ~ Old World"s,
    "Plain Asia"s,
    "Retribution for the Eternal Night ~ Imperishable Night"s,
    "Maiden's Capriccio ~ Dream Battle"s,
    "Love-Colored Master Spark"s,
    "Cinderella Cage ~ Kagome-Kagome"s,
    "Lunatic Eyes ~ Invisible Full Moon"s,
    "Voyage 1969"s,
    "Gensokyo Millennium ~ History of the Moon"s,
    "Flight of the Bamboo Cutter ~ Lunatic Princess"s,
    "Voyage 1970"s,
    "Extend Ash ~ Person of Hourai"s,
    "Reach for the Moon, Immortal Smoke"s,
    "Evening Primrose"s,
    "Eternal Dream ~ Mystical Maple"s,
    "Eastern Youkai Beauty"s,
};

// Touhou 08 Spell Cards
export const vector<string> th08_spellCardName = {
    // stage 1 (13 cards)
    "Firefly Sign \"Meteors on Earth\""s,
    "Firefly Sign \"Comets on Earth\""s,
    "Lamp Sign \"Firefly Phenomenon\""s,
    "Lamp Sign \"Firefly Phenomenon\""s,
    "Lamp Sign \"Firefly Phenomenon\""s,
    "Lamp Sign \"Firefly Phenomenon\""s,
    "Wriggle Sign \"Little Bug\""s,
    "Wriggle Sign \"Little Bug Storm\""s,
    "Wriggle Sign \"Night Bug Storm\""s,
    "Wriggle Sign \"Night Bug Tornado\""s,
    "Hidden Bug \"Endless Night Seclusion\""s,
    "Hidden Bug \"Endless Night Seclusion\""s,
    "Hidden Bug \"Endless Night Seclusion\""s,
    // stage 2 (19 cards)
    "Vocal Sign \"Hooting in the Night\""s,
    "Vocal Sign \"Hooting in the Night\""s,
    "Vocal Sign \"Howl of the Horned Owl\""s,
    "Vocal Sign \"Howl of the Horned Owl\""s,
    "Moth Sign \"Hawk Moth's Insect Curse\""s,
    "Moth Sign \"Hawk Moth's Insect Curse\""s,
    "Toxin Sign \"Poisonous Moth's Scales\""s,
    "Deadly Toxin \"Poisonous Moth's Dance in the Dark\""s,
    "Hawk Sign \"Ill - Starred Dive\""s,
    "Hawk Sign \"Ill - Starred Dive\""s,
    "Hawk Sign \"Ill - Starred Dive\""s,
    "Hawk Sign \"Ill - Starred Dive\""s,
    "Night-Blindness \"Song of the Night Sparrow\""s,
    "Night-Blindness \"Song of the Night Sparrow\""s,
    "Night-Blindness \"Song of the Night Sparrow\""s,
    "Night-Blindness \"Song of the Night Sparrow\""s,
    "Night Sparrow \"Midnight Chorus Master\""s,
    "Night Sparrow \"Midnight Chorus Master\""s,
    "Night Sparrow \"Midnight Chorus Master\""s,
    // stage 3 (22 cards)
    "Spiritual Birth \"First Pyramid\""s,
    "Spiritual Birth \"First Pyramid\""s,
    "Spiritual Birth \"First Pyramid\""s,
    "Spiritual Birth \"First Pyramid\""s,
    "Origin Sign \"Ephemerality 137\""s,
    "Origin Sign \"Ephemerality 137\""s,
    "Origin Sign \"Ephemerality 137\""s,
    "Ambition Sign \"Buretsu Crisis\""s,
    "Ambition Sign \"Masakado Crisis\""s,
    "Ambition Sign \"Yoshimitsu Crisis\""s,
    "Ambition Sign \"General Headquarters Crisis\""s,
    "Land Sign \"Three Sacred Treasures - Sword\""s,
    "Land Sign \"Three Sacred Treasures - Orb\""s,
    "Land Sign \"Three Sacred Treasures - Mirror\""s,
    "Land Scheme \"Three Sacred Treasures - Country\""s,
    "Ending Sign \"Phantasmal Emperor\""s,
    "Ending Sign \"Phantasmal Emperor\""s,
    "Pseudo-History \"The Legend of Gensokyo\""s,
    "Pseudo-History \"The Legend of Gensokyo\""s,
    "Future \"Gods' Realm\""s,
    "Future \"Gods' Realm\""s,
    "Future \"Gods' Realm\""s,
    // stage 4A (23 cards)
    "Dream Sign \"Duplex Barrier\""s,
    "Dream Sign \"Duplex Barrier\""s,
    "Dream Sign \"Great Duplex Barrier\""s,
    "Dream Sign \"Great Duplex Barrier\""s,
    "Spirit Sign \"Fantasy Seal -Spread-\""s,
    "Spirit Sign \"Fantasy Seal -Spread-\""s,
    "Scattered Spirit \"Fantasy Seal -Worn-\""s,
    "Scattered Spirit \"Fantasy Seal -Worn-\""s,
    "Dream Sign \"Evil - Sealing Circle\""s,
    "Dream Sign \"Evil - Sealing Circle\""s,
    "Divine Arts \"Omnidirectional Oni - Binding Circle\""s,
    "Divine Arts \"Omnidirectional Oni - Binding Circle\""s,
    "Spirit Sign \"Fantasy Seal -Concentrate-\""s,
    "Spirit Sign \"Fantasy Seal -Concentrate-\""s,
    "Migrating Spirit \"Fantasy Seal -Marred-\""s,
    "Migrating Spirit \"Fantasy Seal -Marred-\""s,
    "Boundary \"Duplex Danmaku Barrier\""s,
    "Boundary \"Duplex Danmaku Barrier\""s,
    "Great Barrier \"Hakurei Danmaku Barrier\""s,
    "Great Barrier \"Hakurei Danmaku Barrier\""s,
    "Divine Spirit \"Fantasy Seal -Blink-\""s,
    "Divine Spirit \"Fantasy Seal -Blink-\""s,
    "Divine Spirit \"Fantasy Seal -Blink-\""s,
    // stage 4B (23 cards)
    "Magic Sign \"Milky Way\""s,
    "Magic Sign \"Milky Way\""s,
    "Magic Space \"Asteroid Belt\""s,
    "Magic Space \"Asteroid Belt\""s,
    "Magic Sign \"Stardust Reverie\""s,
    "Magic Sign \"Stardust Reverie\""s,
    "Black Magic \"Event Horizon\""s,
    "Black Magic \"Event Horizon\""s,
    "Love Sign \"Non - Directional Laser\""s,
    "Love Sign \"Non - Directional Laser\""s,
    "Love Storm \"Starlight Typhoon\""s,
    "Love Storm \"Starlight Typhoon\""s,
    "Love Sign \"Master Spark\""s,
    "Love Sign \"Master Spark\""s,
    "Loving Heart \"Double Spark\""s,
    "Loving Heart \"Double Spark\""s,
    "Light Sign \"Earthlight Ray\""s,
    "Light Sign \"Earthlight Ray\""s,
    "Light Blast \"Shoot the Moon\""s,
    "Light Blast \"Shoot the Moon\""s,
    "Magicannon \"Final Spark\""s,
    "Magicannon \"Final Spark\""s,
    "Magicannon \"Final Master Spark\""s,
    // stage 5 (19 cards)
    "Wave Sign \"Red-Eyed Hypnosis (Mind Shaker)\""s,
    "Wave Sign \"Red-Eyed Hypnosis (Mind Shaker)\""s,
    "Illusion Wave \"Red-Eyed Hypnosis (Mind Blowing)\""s,
    "Illusion Wave \"Red-Eyed Hypnosis (Mind Blowing)\""s,
    "Lunatic Sign \"Hallucinogenic Tuning (Visionary Tuning)\""s,
    "Lunatic Sign \"Hallucinogenic Tuning (Visionary Tuning)\""s,
    "Lunatic Gaze \"Lunatic Stare Tuning (Illusion Seeker)\""s,
    "Lunatic Gaze \"Lunatic Stare Tuning (Illusion Seeker)\""s,
    "Loafing Sign \"Life and Spirit Stopping (Idling Wave)\""s,
    "Loafing Sign \"Life and Spirit Stopping (Idling Wave)\""s,
    "Indolence \"Life and Spirit Stopping (Mind Stopper)\""s,
    "Indolence \"Life and Spirit Stopping (Mind Stopper)\""s,
    "Spread Sign \"Moon of Truth (Invisible Full Moon)\""s,
    "Spread Sign \"Moon of Truth (Invisible Full Moon)\""s,
    "Spread Sign \"Moon of Truth (Invisible Full Moon)\""s,
    "Spread Sign \"Moon of Truth (Invisible Full Moon)\""s,
    "Lunar Eyes \"Lunar Rabbit's Remote Mesmerism (Tele-Mesmerism)\""s,
    "Lunar Eyes \"Lunar Rabbit's Remote Mesmerism (Tele-Mesmerism)\""s,
    "Lunar Eyes \"Lunar Rabbit's Remote Mesmerism (Tele-Mesmerism)\""s,
    // stage 6A (28 cards)
    "Spacesphere \"Earth in a Pot\""s,
    "Spacesphere \"Earth in a Pot\""s,
    "Spacesphere \"Earth in a Pot\""s,
    "Spacesphere \"Earth in a Pot\""s,
    "Awakened God \"Memories of the Age of the Gods\""s,
    "Awakened God \"Memories of the Age of the Gods\""s,
    "God Sign \"Genealogy of the Celestials\""s,
    "God Sign \"Genealogy of the Celestials\""s,
    "Revival \"Seimei Yugi -Life Game- \""s,
    "Revival \"Seimei Yugi -Life Game- \""s,
    "Resurrection \"Rising Game\""s,
    "Resurrection \"Rising Game\""s,
    "Leading God \"Omoikane's Device\""s,
    "Leading God \"Omoikane's Device\""s,
    "Mind of God \"Omoikane's Brain\""s,
    "Mind of God \"Omoikane's Brain\""s,
    "Curse of the Heavens \"Apollo 13\""s,
    "Curse of the Heavens \"Apollo 13\""s,
    "Curse of the Heavens \"Apollo 13\""s,
    "Curse of the Heavens \"Apollo 13\""s,
    "Esoterica \"Astronomical Entombing\""s,
    "Esoterica \"Astronomical Entombing\""s,
    "Esoterica \"Astronomical Entombing\""s,
    "Esoterica \"Astronomical Entombing\""s,
    "Forbidden Elixir \"Hourai Elixir\""s,
    "Forbidden Elixir \"Hourai Elixir\""s,
    "Forbidden Elixir \"Hourai Elixir\""s,
    "Forbidden Elixir \"Hourai Elixir\""s,
    // stage 6B (44 cards)
    "Medicine Sign \"Galaxy in a Pot\""s,
    "Medicine Sign \"Galaxy in a Pot\""s,
    "Medicine Sign \"Galaxy in a Pot\""s,
    "Medicine Sign \"Galaxy in a Pot\""s,
    "Impossible Request \"Jewel from the Dragon's Neck -Five-Colored Shots-\""s,
    "Impossible Request \"Jewel from the Dragon's Neck -Five-Colored Shots-\""s,
    "Divine Treasure \"Divine Dragon Bullet\""s,
    "Divine Treasure \"Divine Dragon Bullet\""s,
    "Impossible Request \"Buddha's Stone Bowl -Indomitable Will-\""s,
    "Impossible Request \"Buddha's Stone Bowl -Indomitable Will-\""s,
    "Divine Treasure \"Buddhist Diamond\""s,
    "Divine Treasure \"Buddhist Diamond\""s,
    "Impossible Request \"Robe of Fire Rat -Unhurried Mind-\""s,
    "Impossible Request \"Robe of Fire Rat -Unhurried Mind-\""s,
    "Divine Treasure \"Salamander Shield\""s,
    "Divine Treasure \"Salamander Shield\""s,
    "Impossible Request \"Swallow's Cowrie Shell -Everlasting Life-\""s,
    "Impossible Request \"Swallow's Cowrie Shell -Everlasting Life-\""s,
    "Divine Treasure \"Life Spring Infinity\""s,
    "Divine Treasure \"Life Spring Infinity\""s,
    "Impossible Request \"Bullet Branch of Hourai -Rainbow Danmaku -\""s,
    "Impossible Request \"Bullet Branch of Hourai -Rainbow Danmaku -\""s,
    "Divine Treasure \"Jeweled Branch of Hourai -Dreamlike Paradise-\""s,
    "Divine Treasure \"Jeweled Branch of Hourai -Dreamlike Paradise-\""s,
    "\"End of Imperishable Night -New Moon-\""s,
    "\"End of Imperishable Night -Crescent Moon-\""s,
    "\"End of Imperishable Night -First Quarter's Moon-\""s,
    "\"End of Imperishable Night -Matsuyoi-\""s,
    "\"End of Imperishable Night -11 o'Clock-\""s,
    "\"End of Imperishable Night -Half to Midnight-\""s,
    "\"End of Imperishable Night -Midnight-\""s,
    "\"End of Imperishable Night -Half Past Midnight-\""s,
    "\"End of Imperishable Night -1 o'Clock-\""s,
    "\"End of Imperishable Night -Half Past 1-\""s,
    "\"End of Imperishable Night -Dead of Night-\""s,
    "\"End of Imperishable Night -Half Past 2-\""s,
    "\"End of Imperishable Night -3 o'Clock-\""s,
    "\"End of Imperishable Night -Half Past 3-\""s,
    "\"End of Imperishable Night -4 o'Clock-\""s,
    "\"End of Imperishable Night -Half Past 4-\""s,
    "\"End of Imperishable Night -Morning Mist-\""s,
    "\"End of Imperishable Night -Dawn-\""s,
    "\"End of Imperishable Night -Morning Star-\""s,
    "\"End of Imperishable Night -Rising World-\""s,
    // extra stage (14 cards)
    "Past \"Old History of an Untrodden Land -Old History-\""s,
    "Reincarnation \"Ichijou Returning Bridge\""s,
    "Future \"New History of Fantasy -Next History-\""s,
    "Limiting Edict \"Curse of Tsuki-no-Iwakasa\""s,
    "Undying \"Fire Bird -Feng Wing Ascension-\""s,
    "Fujiwara \"Wounds of Metsuzai Temple\""s,
    "Undying \"Xu Fu's Dimension\""s,
    "Expiation \"Honest Man's Death\""s,
    "Hollow Being \"Wu\""s,
    "Inextinguishable \"Phoenix's Tail\""s,
    "Hourai \"South Wind, Clear Sky -Fujiyama Volcano-\""s,
    "\"Possessed by Phoenix\""s,
    "\"Hourai Doll\""s,
    "\"Imperishable Shooting\""s,
    // last words (17 cards)
    "\"Unseasonal Butterfly Storm\""s,
    "\"Blind Nightbird\""s,
    "\"Emperor of the Land of the Rising Sun\""s,
    "\"Stare of the Hazy Phantom Moon (Lunatic Red Eyes)\""s,
    "\"Heaven Spider's Butterfly-Capturing Web\""s,
    "\"Tree-Ocean of Hourai\""s,
    "\"Phoenix Rebirth\""s,
    "\"Ancient Duper\""s,
    "\"Total Purification\""s,
    "\"Fantasy Nature\""s,
    "\"Blazing Star\""s,
    "\"Deflation World\""s,
    "\"Matsuyoi-Reflecting Satellite Slash\""s,
    "\"The Phantom of the Grand Guignol\""s,
    "\"Scarlet Destiny\""s,
    "\"Saigyouji Parinirvana\""s,
    "\"Profound Danmaku Barrier -Phantasm, Foam and Shadow-\""
};

// Touhou 09 Music
export const vector<string> th09_musicNames = {
    "Flower Reflecting Mound ~ Higan Retour"s,
    "Spring Lane ~ Colorful Path"s,
    "Oriental Dark Flight"s,
    "Flowering Night"s,
    "Eastern Ghostly Dream ~ Ancient Temple"s,
    "Lunatic Eyes ~ Invisible Full Moon"s,
    "Adventure of the Lovestruck Tomboy"s,
    "Phantom Band ~ Phantom Ensemble"s,
    "Deaf to All but the Song ~ Flower Mix"s,
    "White Flag of Usa Shrine"s,
    "Wind God Girl"s,
    "Poison Body ~ Forsaken Doll"s,
    "Gensokyo, Past and Present ~ Flower Land"s,
    "Higan Retour ~ Riverside View"s,
    "Eastern Judgement in the Sixtieth Year ~ Fate of Sixty Years"s,
    "The Mound where the Flowers Reflect"s,
    "Mound of Shigan"s,
    "The Flowers Remain in Fantasy"s,
    "Flower of Soul ~ Another Dream..."s,
};

// Touhou 09 Stages
export const vector<string> th09_stageNames = {
    "Bamboo Forest of the Lost"s,
    "Bamboo Forest of the Lost"s,
    "Phantom Meadow"s,
    "Hakugyokurou's Stairway"s,
    "Eientei"s,
    "Misty Lake"s,
    "Barrier of Life & Death"s,
    "Youkai Trail"s,
    "Bamboo Forest of the Lost"s,
    "Garden of the Sun"s,
    "Giant Toad's Pond"s,
    "The Nameless Hill"s,
    "Road of Reconsideration"s,
    "Muenzuka"s,
};

// Touhou 09 Characters
export const vector<string> th09_characterNames = {
    "Reimu"s,
    "Marisa"s,
    "Sakuya"s,
    "Youmu"s,
    "Reisen"s,
    "Cirno"s,
    "Lyrica"s,
    "Mystia"s,
    "Tewi"s,
    "Yuuka"s,
    "Aya"s,
    "Medicine"s,
    "Komachi"s,
    "Eiki"s,
    "Merlin"s,
    "Lunasa"s,
};


// Touhou 09.5 Bosses and Spells
// Empty strings are for unused levels.
export const vector<string> th095_bossAndSpells = {
    // Level 1
    "Wriggle Nightbug"s,
    "Rumia"s,
    "Wriggle Nightbug - Firefly Sign \"Fixed Stars on Earth\""s,
    "Rumia - Darkness Sign \"Dark Side of the Moon\""s,
    "Wriggle Nightbug - Butterfly Sign \"Butterfly Storm\""s,
    "Rumia - Night Sign \"Midnight Bird\""s,
    ""s,
    ""s,
    ""s,
    ""s,
    // Level 2
    "Cirno"s,
    "Letty Whiterock"s,
    "Cirno - Snow Sign \"Diamond Blizzard\""s,
    "Letty Whiterock - Cold Sign \"Cold Snap\""s,
    "Cirno - Freeze Sign \"Minus K\""s,
    "Letty Whiterock - Winter Sign \"Northern Winner\""s,
    ""s,
    ""s,
    ""s,
    ""s,
    // Level 3
    "Alice Margatroid"s,
    "Keine Kamishirasawa - Light Sign \"Amaterasu\""s,
    "Alice Margatroid - Puppeteer Sign \"Dolls in Sea\""s,
    "Keine Kamishirasawa - Shroud Sign \"Rain of Showa\""s,
    "Alice Margatroid - Curse Sign \"Straw Doll Kamikaze\""s,
    "Keine Kamishirasawa - Hollyhock Sign \"Mito no Mitsukuni\""s,
    "Alice Margatroid - Red Sign \"Doll Mira Ceti\""s,
    "Keine Kamishirasawa - Japan Sign \"Yamato Kingdom\""s,
    ""s,
    ""s,
    // Level 4
    "Reisen Udongein Inaba"s,
    "Medicine Melancholy - Fog Sign \"Gassing Garden\""s,
    "Tewi Inaba - Runaway Rabbit \"Fluster Escape\""s,
    "Reisen Udongein Inaba - Spread Sign \"Hazy Moon Flower Bookmark (Rocket in Mist)\""s,
    "Medicine Melancholy - Poison Sign \"Poison Breath\""s,
    "Reisen Udongein Inaba - Wave Sign \"Moon of Illusion (Invisible Half-Moon)\""s,
    "Medicine Melancholy - Confusion \"Into Delirium\""s,
    "Tewi Inaba - Owing Sign \"Vulnerary of Oonamuchi-sama\""s,
    "Reisen Udongein Inaba - Mad Dream \"Dream of Insanity (Dream World)\""s,
    ""s,
    // Level 5
    "Hong Meiling"s,
    "Patchouli Knowledge - Sun & Water Sign \"Hydrogenous Prominence\""s,
    "Hong Meiling - Flower Sign \"Colorful Light Lotus Flower Palm\""s,
    "Patchouli Knowledge - Water & Fire Sign \"Phlogistic Rain\""s,
    "Hong Meiling - Colorful Flip \"Fluttering Petals and Falling Leaves\""s,
    "Patchouli Knowledge - Moon & Wood Sign \"Satellite Himawari\""s,
    "Hong Meiling - Colorful Chinese Flower \"Rainbow Taijiquan\""s,
    "Patchouli Knowledge - Sun & Moon Sign \"Royal Diamond Ring\""s,
    ""s,
    ""s,
    // Level 6
    "Chen"s,
    "Youmu Konpaku - Human Knowledge Sword \"Turning Angel Cut\""s,
    "Chen - Star Sign \"Leaping Kasane-Uroko Star\""s,
    "Youmu Konpaku - Obsession Sword \"Blood of Asura\""s,
    "Chen - Kishin \"Rumbling Jikokuten\""s,
    "Youmu Konpaku - Celestial Star Sword \"As the Silent Nirvana\""s,
    "Chen - Bakeneko \"Chen\""s,
    "Youmu Konpaku - Four Births Sword \"Echoes of the Inclemency of All Beings\""s,
    ""s,
    ""s,
    // Level 7
    "Sakuya Izayoi"s,
    "Remilia Scarlet - Devil Sign \"All the World in Nightmare\""s,
    "Sakuya Izayoi - Time Sign \"Tunnel Effect\""s,
    "Remilia Scarlet - Scarlet Sign \"Bloody Magic Square\""s,
    "Sakuya Izayoi - Void \"Inflation Square\""s,
    "Remilia Scarlet - Scarlet Bat \"Vampirish Night\""s,
    "Sakuya Izayoi - Silver Sign \"Perfect Maid\""s,
    "Remilia Scarlet - God Devil \"Remilia Stoker\""s,
    ""s,
    ""s,
    // Level 8
    "Ran Yakumo"s,
    "Yuyuko Saigyouji - Ghostly Elegance \"Light Trap of Passing Away\""s,
    "Ran Yakumo - Esoteric Sign \"Odaishi-sama's Secret Key\""s,
    "Yuyuko Saigyouji - Butterfly Sign \"Deadly Lance of the Swallowtail Butterfly Crest\""s,
    "Ran Yakumo - Ascetic Sign \"Eighty Million Goma Boards\""s,
    "Yuyuko Saigyouji - Death Sign \"Life of Drunk, Dream of Death\""s,
    "Ran Yakumo - Superman \"Soaring En no Ozunu\""s,
    "Yuyuko Saigyouji - \"Death Butterfly, Floating Moon\""s,
    ""s,
    ""s,
    // Level 9
    "Eirin Yagokoro"s,
    "Kaguya Houraisan - New Impossible Request \"Lunar Ilmenite\""s,
    "Eirin Yagokoro - Medicine Sign \"Butterfly Dream Pill - Nightmare Type\""s,
    "Kaguya Houraisan - New Impossible Request \"Red Stone of Aja\""s,
    "Eirin Yagokoro - Elixir \"Mercury Sea\""s,
    "Kaguya Houraisan - New Impossible Request \"Seamless Ceiling of Kinkaku-ji\""s,
    "Eirin Yagokoro - Secret Elixir \"Lunar Incense\""s,
    "Kaguya Houraisan - New Impossible Request \"Mysterium\""s,
    ""s,
    ""s,
    // Level 10
    "Komachi Onozuka"s,
    "Eiki Shiki, Yamaxanadu - Lie \"Tongue of Wolf\""s,
    "Komachi Onozuka - Death Song \"Ferry of the Deep Fog\""s,
    "Eiki Shiki, Yamaxanadu - Judgment \"Trial of the Ten Kings\""s,
    "Komachi Onozuka - Old Rain \"Rain in the Liminal Journey Through Yomi\""s,
    "Eiki Shiki, Yamaxanadu - Judgment \"Guilty or Not Guilty\""s,
    "Komachi Onozuka - Death Price \"Price of Life\""s,
    "Eiki Shiki, Yamaxanadu - Judgment \"Cleansed Crystal Judgment -Aya Shameimaru-\""s,
    ""s,
    ""s,
    // Level EX
    "Flandre Scarlet - Taboo \"Forbidden Fruit\""s,
    "Flandre Scarlet - Taboo \"Forbidden Games\""s,
    "Yukari Yakumo - Boundary Sign \"Boundary of Form and Emptiness\""s,
    "Yukari Yakumo - Boundary Sign \"Boundary of Wave and Particle\""s,
    "Fujiwara no Mokou - Exalted Personage \"Forewarning of St.Germain\""s,
    "Fujiwara no Mokou - Hourai \"Mizunoe no Uranoshimako and Five-Colored Turtles\""s,
    "Suika Ibuki - Ghastly Air \"Deep Fog Labyrinth\""s,
    "Suika Ibuki - \"Night Parade of a Million Demons\""s,
    ""s,
    ""s,
};

// Touhou 09.5 Music
export const vector<string> th095_musicNames = {
    "Tengu's Notebook ~ Mysterious Note"s,
    "Wind Circulation ~ Wind Tour"s,
    "Tengu is Watching ~ Black Eyes"s,
    "Sleepless Night of the Eastern Country"s,
    "Retrospective Kyoto"s,
    "Wind God Girl"s,
};

// Touhou 10
export const vector<string> th10_musicNames = {
    "A God That Misses People ~ Romantic Fall"s,
    "Because Princess Inada Is Scolding Me"s,
    "Sealed Gods"s,
    "The Road of the Misfortune God ~ Dark Road"s,
    "Dark Side of Fate"s,
    "The Gensokyo the Gods Loved"s,
    "Akutagawa Ryuunosuke's \"Kappa\" ~ Candid Friend"s,
    "Fall of Fall ~ Autumnal Waterfall"s,
    "Youkai Mountain ~ Mysterious Mountain"s,
    "The Primal Scene of Japan the Girl Saw"s,
    "Faith Is for the Transient People"s,
    "Cemetery of Onbashira ~ Grave of Being"s,
    "The Venerable Ancient Battlefield ~ Suwa Foughten Field"s,
    "Shrine at the Foot of the Mountain"s,
    "The Gods Give Us Blessed Rain ~ Sylphid Dream"s,
    "Tomorrow Will Be Special, Yesterday Was Not"s,
    "Native Faith"s,
    "Player's Score"s,
};

// Touhou 11
export const vector<string> th11_musicNames = {
    "Awakening of the Earth Spirits"s,
    "The Dark Blowhole"s,
    "The Sealed Youkai ~ Lost Place"s,
    "The Bridge People No Longer Cross"s,
    "unused"s,
    "Green-Eyed Jealousy"s,
    "Walking the Streets of a Former Hell"s,
    "A Flower-Studded Sake Dish on Mt. Ooe"s,
    "Heartfelt Fancy"s,
    "unused"s,
    "Satori Maiden ~ 3rd eye"s,
    "unused"s,
    "Lullaby of Deserted Hell"s,
    "Corpse Voyage ~ Be of good cheer!"s,
    "Hellfire Mantle"s,
    "Last Remote"s,
    "Solar Sect of Mystic Wisdom ~ Nuclear Fusion"s,
    "Hartmann's Youkai Girl"s,
    "The Earth Spirits' Homecoming"s,
    "Energy Daybreak ~ Future Dream..."s,
};

// Touhou 12
export const vector<string> th12_musicNames = {
    "At the End of Spring"s,
    "A Shadow in the Blue Sky"s,
    "A Tiny, Tiny, Clever Commander"s,
    "unused"s,
    "The Sealed Cloud Route"s,
    "Beware the Umbrella Left There Forever"s,
    "unused"s,
    "Sky Ruin"s,
    "The Traditional Old Man and the Stylish Girl"s,
    "Interdimensional Voyage of a Ghostly Passenger Ship"s,
    "Captain Murasa"s,
    "unused"s,
    "unused"s,
    "Rural Makai City Esoteria"s,
    "The Tiger-Patterned Bishamonten"s,
    "unused"s,
    "Fires of Hokkai"s,
    "Emotional Skyscraper ~ Cosmic Mind"s,
    "UFO Romance in the Night Sky"s,
    "Heian Alien"s,
    "Youkai Temple"s,
    "Returning Home from the Sky ~ Sky Dream"s,
};

// Touhou 12.5 Music
export const vector<string> th125_musicNames = {
    "Newshound"s,
    "The Mystery in Your Town"s,
    "Youkai Modern Colony"s,
    "Nemesis's Stronghold"s,
    "Bell of Avici ~ Infinite Nightmare"s,
    "Youkai Mountain ~ Mysterious Mountain"s,
};

// Touhou 12.5 Bosses and Spells
// Empty strings are for unused levels.
export const vector<string> th125_bossAndSpells = {
    // Level 1
    "Minoriko Aki"s,
    "Minoriko Aki"s,
    "Shizuha Aki - Autumn Sign \"Falling Blast\""s,
    "Minoriko Aki - Fruit Sign \"Warm Colour Harvest\""s,
    "Shizuha Aki - Wilted Path \"Lost Windrow\""s,
    "Minoriko Aki - Baked Sweet Potato \"Sweet Potato Room\""s,
    ""s,
    ""s,
    ""s,
    ""s,
    // Level 2
    "Parsee Mizuhashi"s,
    "Hina Kagiyama"s,
    "Parsee Mizuhashi - Jealousy \"Jealousy Bomber\""s,
    "Hina Kagiyama - Cursed Field \"Purification River Deposit\""s,
    "Parsee Mizuhashi - Resentment Art \"Grudge Returning\""s,
    "Hina Kagiyama - Calamity \"Cursed Hina Dolls\""s,
    ""s,
    ""s,
    ""s,
    ""s,
    // Level 3
    "Yamame Kurodani"s,
    "Kogasa Tatara - Umbrella Sign \"One-Legged Return Hit\""s,
    "Kisume - Well Bucket \"Like a Moth to a Well\""s,
    "Yamame Kurodani - Small Thread \"Kandata's Rope\""s,
    "Kogasa Tatara - Rainbow Sign \"Over The Rainbow\""s,
    "Kisume - Well Bucket \"Well Destructor\""s,
    "Yamame Kurodani - Poison Sign \"Japanese Foliage Spider\""s,
    "Kogasa Tatara - Umbrella Sign \"Flurry Travelers\""s,
    ""s,
    ""s,
    // Level 4
    "Nitori Kawashiro"s,
    "Momiji Inubashiri"s,
    "Nitori Kawashiro - Water Sign \"Water Carpet\""s,
    "Momiji Inubashiri - Dog Sign \"Rabies Bite\""s,
    "Nitori Kawashiro - River Sign \"Dividing Edge\""s,
    "Momiji Inubashiri - Mountain Nomad \"Expellee's Canaan\""s,
    "Nitori Kawashiro - Kappa \"Dried Shirikodama\""s,
    ""s,
    ""s,
    ""s,
    // Level 5
    "Ichirin Kumoi"s,
    "Minamitsu Murasa"s,
    "Ichirin Kumoi - Fist \"Falling Sky Hammer\""s,
    "Minamitsu Murasa - Anchor Sign \"Phantom Ship's Long-Term Anchorage\""s,
    "Ichirin Kumoi - Lightning \"Electrified Nyuudou\""s,
    "Minamitsu Murasa - Flood \"Venus of the Bilge\""s,
    "Ichirin Kumoi - Iron Fist \"Nyuudou Nyoki\""s,
    "Minamitsu Murasa - \"Deep Sinker\""s,
    ""s,
    ""s,
    // Level 6
    "Yuugi Hoshiguma"s,
    "Suika Ibuki"s,
    "Yuugi Hoshiguma - Light Oni \"Adamant Helix\""s,
    "Suika Ibuki - Oni Sign \"Pea-Sized Needle Hell\""s,
    "Yuugi Hoshiguma - Oni Sign \"Dreadful Raging Waves\""s,
    "Suika Ibuki - Hell \"Purgatorial Sigh\""s,
    "Yuugi Hoshiguma - Oni's Voice \"Annihilating Roar\""s,
    "Suika Ibuki - Oni Sign \"Missing Power\""s,
    ""s,
    ""s,
    // Level 7
    "Shou Toramaru"s,
    "Nazrin"s,
    "Shou Toramaru - Tiger Sign \"Hungry Tiger\""s,
    "Nazrin - Rod Sign \"Nazrin Rod\""s,
    "Shou Toramaru - Heaven Sign \"Scorched Earth Mandala\""s,
    "Nazrin - Treasure \"Gold Rush\""s,
    "Shou Toramaru - Treasure Sign \"Dazzling Gold\""s,
    ""s,
    ""s,
    ""s,
    // Level 8
    "Rin Kaenbyou"s,
    "Utsuho Reiuji - Fusion \"Melting White\""s,
    "Rin Kaenbyou - Death Sign \"Ghost Town\""s,
    "Utsuho Reiuji - Giant Star \"Red Giant\""s,
    "Rin Kaenbyou - \"Corpse Shopping District\""s,
    "Utsuho Reiuji - Star Sign \"Fall of Great Stars\""s,
    "Rin Kaenbyou - Drunkard's Walk \"Cat Random Walk\""s,
    "Utsuho Reiuji - Seven Stars \"Septentrion\""s,
    ""s,
    ""s,
    // Level 9
    "Satori Komeiji"s,
    "Koishi Komeiji - Heart Sign \"Selfless Love\""s,
    "Satori Komeiji - Brain Sign \"Brain Fingerprint\""s,
    "Koishi Komeiji - Memory \"DNA's Flaw\""s,
    "Satori Komeiji - Heart Flower \"Camera - Shy Rose\""s,
    "Koishi Komeiji - \"Embryo's Dream\""s,
    "Satori Komeiji - Recollection \"Vague Recollection of Kinkaku-ji\""s,
    "Koishi Komeiji - \"Rose Hell\""s,
    ""s,
    ""s,
    // Level 10
    "Tenshi Hinanawi - Temperament \"High-Spirited Sword"s,
    "Iku Nagae - Thunder Sign \"Lightning Fish\""s,
    "Tenshi Hinanawi - Earthquake \"Escarpment Evacuation Route\""s,
    "Iku Nagae - Orb Sign \"Orb of the Five-Clawed Dragon\""s,
    "Tenshi Hinanawi - Keystone \"Kaname Funnel\""s,
    "Iku Nagae - Dragon Palace \"Dance of Sea Breams and Flounders\""s,
    "Tenshi Hinanawi - \"Sky of Scarlet Perception of All Humankind\""s,
    "Iku Nagae - Dragon Fish \"Oarfish's Swimming Shot\""s,
    ""s,
    ""s,
    // Level 11
    "Kanako Yasaka"s,
    "Suwako Moriya - Divine Sakura \"Full Sakura Blizzard\""s,
    "Kanako Yasaka - Snake Sign \"Ground Serpent\""s,
    "Suwako Moriya - Hime River \"Princess Jade Green\""s,
    "Kanako Yasaka - Divine Pillar \"Meteoric Onbashira\""s,
    "Suwako Moriya - Iron Ring \"Mythical Ring\""s,
    "Kanako Yasaka - Fleeting Path \"Omiwatari Cross\""s,
    "Suwako Moriya - Native God \"Mishaguji-sama\""s,
    ""s,
    ""s,
    // Level 12
    "Byakuren Hijiri"s,
    "Nue Houjuu - Unidentified \"Purple Mirror\""s,
    "Byakuren Hijiri - \"Yuugyou Hijiri\""s,
    "Nue Houjuu - Unidentified \"Red Cloak, Blue Cloak\""s,
    "Byakuren Hijiri - Syncretism \"Manifestation of Mahavairocana\""s,
    "Nue Houjuu - Unidentified \"Ms.Hanako of the Toilet\""s,
    "Byakuren Hijiri - \"Star Sword Apologetics\""s,
    "Nue Houjuu - \"Danmaku X from a Wandering Star\""s,
    ""s,
    ""s,
    // Level EX
    "Reimu Hakurei - Talisman \"Exorcism of the Newspaper Subscription Solicitors\""s,
    "Marisa Kirisame - Star Sign \"Oort Cloud\""s,
    "Sanae Kochiya - Miracle \"Divine Wind of the Kouan Era\""s,
    "Reimu Hakurei - Barrier \"Paparazzi-Repelling Barrier\""s,
    "Marisa Kirisame - Celestial Apparatus \"Orreries Solar System\""s,
    "Sanae Kochiya - Frog Sign \"Wily Toad\""s,
    "Reimu Hakurei - Dream Sign \"Fantasy Dimensional Rift\""s,
    "Marisa Kirisame - Comet \"Blazing Star\""s,
    "Sanae Kochiya - Youkai Extermination \"Youkai Power Spoiler\""s,
    ""s,
    // Level SP (??)
    "Hatate Himekaidou"s,
    "Hatate Himekaidou - Reporting \"Hatate Himekaidou's Reporting Training\""s,
    "Hatate Himekaidou - Continuous Shooting \"Rapid Shot\""s,
    "Hatate Himekaidou - Far-sightedness \"Tengu Psychography\""s,
    "Aya Shameimaru"s,
    "Aya Shameimaru - Reporting \"Aya Shameimaru's Coercive Reporting\""s,
    "Aya Shameimaru - Telescoping \"Candid Shot\""s,
    "Aya Shameimaru - Snapshot \"Fast Shot\""s,
    "Aya Shameimaru - \"Illusionary Dominance\""s,
    ""s,
};

// Touhou 12.8
export const vector<string> th12_8_musicNames = {
    "The Refrain of the Lovely Great War"s,
    "Year-Round Absorbed Curiosity"s,
    "Staking Your Life on a Prank"s,
    "unused"s,
    "unused"s,
    "A Midnight Fairy Dance"s,
    "Great Fairy Wars ~ Fairy Wars"s,
    "An Ice Fairy in Spring"s,
    "Player's Score"s,
    "An Ice Fairy in Spring - still -"s,
    "Loose Rain"s,
    "Magus Night"s,
};

// Touhou 13
export const vector<string> th13_spellCardName = {
    // stage 1 (14 cards)
    "Symbol \"Dance of the Dead Butterflies\""s,
    "Symbol \"Dance of the Dead Butterflies\""s,
    "Symbol \"Dance of the Dead Butterflies - Cherry Blossoms -\""s,
    "Symbol \"Dance of the Dead Butterflies - Cherry Blossoms -\""s,
    "Ghostly Butterfly \"Ghost Spot\""s,
    "Ghostly Butterfly \"Ghost Spot\""s,
    "Ghostly Butterfly \"Ghost Spot - Cherry Blossoms -\""s,
    "Ghostly Butterfly \"Ghost Spot - Cherry Blossoms -\""s,
    "Nether Sign \"Endless Evening Cherry Blossoms\""s,
    "Nether Sign \"Endless Evening Cherry Blossoms\""s,
    "Nether Sign \"Endless Evening Cherry Blossoms\""s,
    "Nether Sign \"Endless Evening Cherry Blossoms\""s,
    "Cherry Blossom Sign \"Saigyou Cherry Blossom Blizzard\""s,
    "Cherry Blossom Sign \"Saigyou Cherry Blossom Blizzard\""s,
    // stage 2 (16 cards)
    "Echo Sign \"Mountain Echo\""s,
    "Echo Sign \"Mountain Echo\""s,
    "Echo Sign \"Mountain Echo Scramble\""s,
    "Echo Sign \"Mountain Echo Scramble\""s,
    "Echo Sign \"Power Resonance\""s,
    "Echo Sign \"Power Resonance\""s,
    "Echo Sign \"Power Resonance\""s,
    "Echo Sign \"Power Resonance\""s,
    "Mountain Echo \"Long-Range Echo\""s,
    "Mountain Echo \"Long-Range Echo\""s,
    "Mountain Echo \"Amplify Echo\""s,
    "Mountain Echo \"Amplify Echo\""s,
    "Great Voice \"Charged Cry\""s,
    "Great Voice \"Charged Cry\""s,
    "Great Voice \"Charged Yahoo!\""s,
    "Great Voice \"Charged Yahoo!\""s,
    // stage 3 (14 cards)
    "Rainbow Sign \"Umbrella Cyclone\""s,
    "Rainbow Sign \"Umbrella Cyclone\""s,
    "Recovery \"Heal By Desire\""s,
    "Recovery \"Heal By Desire\""s,
    "Recovery \"Heal By Desire\""s,
    "Recovery \"Heal By Desire\""s,
    "Poison Nail \"Poison Raze\""s,
    "Poison Nail \"Poison Raze\""s,
    "Poison Nail \"Poison Murder\""s,
    "Poison Nail \"Poison Murder\""s,
    "Desire Sign \"Score Desire Spirit Invitation\""s,
    "Desire Sign \"Score Desire Spirit Invitation\""s,
    "Desire Sign \"Score Desire Eater\""s,
    "Desire Sign \"Score Desire Eater\""s,
    // stage 4 (15 cards)
    "Evil Sign \"Yang Xiaogui\""s,
    "Evil Sign \"Guhun Yegui\""s,
    "Evil Sign \"Guhun Yegui\""s,
    "Demonify \"Zouhuo Rumo\""s,
    "Demonify \"Zouhuo Rumo\""s,
    "Demonify \"Zouhuo Rumo\""s,
    "Demonify \"Zouhuo Rumo\""s,
    "Possession \"Corpse Tongji\""s,
    "Possession \"Corpse Tongji\""s,
    "Spirit Link \"Tongling Yoshika\""s,
    "Spirit Link \"Tongling Yoshika\""s,
    "Path Sign \"Tao Fetal Movement\""s,
    "Path Sign \"Tao Fetal Movement\""s,
    "Path Sign \"Tao Fetal Movement\""s,
    "Path Sign \"Tao Fetal Movement\""s,
    // stage 5 (19 cards)
    "Thunder Arrow \"Gagouji's Cyclone\""s,
    "Thunder Arrow \"Gagouji's Cyclone\""s,
    "Thunder Arrow \"Gagouji's Tornado\""s,
    "Heaven Sign \"Rainy Iwafune\""s,
    "Heaven Sign \"Rainy Iwafune\""s,
    "Heaven Sign \"Iwafune Ascending to Heaven\""s,
    "Heaven Sign \"Iwafune Ascending to Heaven\""s,
    "Throwing Dishes \"Mononobe's Eighty Sake Cups\""s,
    "Throwing Dishes \"Mononobe's Eighty Sake Cups\""s,
    "Throwing Dishes \"Mononobe's Eighty Sake Cups\""s,
    "Throwing Dishes \"Mononobe's Eighty Sake Cups\""s,
    "Blaze Sign \"Blazing Winds of Haibutsu\""s,
    "Blaze Sign \"Blazing Winds of Haibutsu\""s,
    "Blaze Sign \"Sakuraiji in Flames\""s,
    "Blaze Sign \"Sakuraiji in Flames\""s,
    "Saint Girl \"Oomonoimi's Dinner\""s,
    "Saint Girl \"Oomonoimi's Dinner\""s,
    "Saint Girl \"Oomonoimi's Dinner\""s,
    "Saint Girl \"Oomonoimi's Dinner\""s,
    // stage 6 (28 cards)
    "Honor \"Colors of Twelve Levels\""s,
    "Honor \"Colors of Twelve Levels\""s,
    "Honor \"Ranks of Twelve Levels\""s,
    "Honor \"Ranks of Twelve Levels\""s,
    "Hermit Sign \"Taoist of the Land of the Rising Sun\""s,
    "Hermit Sign \"Taoist of the Land of the Rising Sun\""s,
    "Hermit Sign \"Emperor of the Land of the Rising Sun\""s,
    "Hermit Sign \"Emperor of the Land of the Rising Sun\""s,
    "Summon \"Royal Clan's Chaotic Dance\""s,
    "Summon \"Royal Clan's Chaotic Dance\""s,
    "Summon \"Royal Clan's Chaotic Dance\""s,
    "Summon \"Royal Clan's Chaotic Dance\""s,
    "Secret Treasure \"Armillary Sphere of Ikaruga-dera\""s,
    "Secret Treasure \"Armillary Sphere of Ikaruga-dera\""s,
    "Secret Treasure \"Armillary Sphere of Ikaruga-dera\""s,
    "Secret Treasure \"Prince Shotoku's Out-of-Place Artifact\""s,
    "Light Sign \"Halo of the Guse Kannon\""s,
    "Light Sign \"Halo of the Guse Kannon\""s,
    "Light Sign \"Guse Flash\""s,
    "Light Sign \"Guse Flash\""s,
    "Discernment \"Laser of Seventeen Articles\""s,
    "Discernment \"Laser of Seventeen Articles\""s,
    "Divine Light \"Honour the Avoidance of Defiance\""s,
    "Divine Light \"Honour the Avoidance of Defiance\""s,
    "\"Falling Stars on Divine Spirit Mausoleum\""s,
    "\"Falling Stars on Divine Spirit Mausoleum\""s,
    "\"Newborn Divine Spirit\""s,
    "\"Newborn Divine Spirit\""s,
    // extra stage (13 cards)
    "Unknown \"Will-o'-wisps in Unknown Orbit\""s,
    "Unknown \"Skyfish with Unknown Shape\""s,
    "Unknown \"Youkai Orb of Unknown Mechanics\""s,
    "First Duel \"Primate Danmaku Transformation\""s,
    "Second Duel \"Carnivorous Danmaku Transformation\""s,
    "Third Duel \"Avian Danmaku Transformation\""s,
    "Fourth Duel \"Amphibian Danmaku Transformation\""s,
    "Fifth Duel \"Scrolls of Frolicking Animals\""s,
    "Sixth Duel \"Tanuki's Monstrous School\""s,
    "Seventh Duel \"Wild Deserted Island\""s,
    "Transformation \"Pseudo-Exorcism of the Stupid Shrine Maiden\""s,
    "\"Mamizou Danmaku in Ten Transformations\""s,
    "Mujina Sign \"Full Moon Pompokolin\""s,
    // OVERDRIVE (8 cards)
    "Cherry Blossom Sign \"Cherry Blossom Blizzard Hell\""s,
    "Mountain Echo \"Yamabiko's Specialty Echo Demonstration\""s,
    "Poison Nail \"Undead Murderer\""s,
    "Path Sign \"TAO Fetal Movement ~Dao~\""s,
    "Vengeful Spirit \"Iruka's Thunder\""s,
    "Saint Girl \"Sun Goddess's Sacrifice\""s,
    "\"Divine Spirits' Macrocosm\""s,
    "\"Wild Carpet\""
};

// Touhou 13 Music
export const vector<string> th13_musicNames = {
    "Spirit of Avarice"s,
    "Night Sakura of Dead Spirits"s,
    "unused"s,
    "Ghost Lead"s,
    "Welcome to Youkai Temple"s,
    "unused"s,
    "Youkai Girl at the Gate"s,
    "Let's Live in a Lovely Cemetery"s,
    "Rigid Paradise"s,
    "unused"s,
    "Desire Drive"s,
    "Old Yuanxian"s,
    "The Hall of Dreams' Great Mausoleum"s,
    "unused"s,
    "unused"s,
    "Omiwa Legend"s,
    "Starry Sky of Small Desires"s,
    "Shoutoku Legend ~ True Administrator"s,
    "A New Wind at the Shrine"s,
    "Desire Dream"s,
    "Youkai Back Shrine Road"s,
    "Futatsuiwa from Sado"s,
};

// Touhou 14 Spell Cards
export const vector<string> th14_spellCardName = {
    // stage 1 (1-10) (10 cards)
    "Ice Sign \"Ultimate Blizzard\""s,
    "Ice Sign \"Ultimate Blizzard\""s,
    "Water Sign \"Tail Fin Slap\""s,
    "Water Sign \"Tail Fin Slap\""s,
    "Water Sign \"Tail Fin Slap\""s,
    "Water Sign \"Tail Fin Slap\""s,
    "Scale Sign \"Scale Wave\""s,
    "Scale Sign \"Scale Wave\""s,
    "Scale Sign \"Raging Waves of the Reversed Scale\""s,
    "Scale Sign \"Great Raging Waves of the Reversed Scale\""s,
    // stage 2 (11-26) (16 cards)
    "Flight Sign \"Flying Head\""s,
    "Flight Sign \"Flying Head\""s,
    "Flight Sign \"Flying Head\""s,
    "Flight Sign \"Flying Head\""s,
    "Neck Sign \"Close - Eye Shot\""s,
    "Neck Sign \"Close - Eye Shot\""s,
    "Neck Sign \"Rokurokubi Flight\""s,
    "Neck Sign \"Rokurokubi Flight\""s,
    "Flying Head \"Multiplicative Head\""s,
    "Flying Head \"Multiplicative Head\""s,
    "Flying Head \"Seventh Head\""s,
    "Flying Head \"Ninth Head\""s,
    "Flying Head \"Dullahan Night\""s,
    "Flying Head \"Dullahan Night\""s,
    "Flying Head \"Dullahan Night\""s,
    "Flying Head \"Dullahan Night\""s,
    // stage 3 (27-40) (14 cards)
    "Fang Sign \"Moonlit Canine Teeth\""s,
    "Fang Sign \"Moonlit Canine Teeth\""s,
    "Transformation \"Triangle Fang\""s,
    "Transformation \"Triangle Fang\""s,
    "Transformation \"Star Fang\""s,
    "Transformation \"Star Fang\""s,
    "Roar \"Strange Roar\""s,
    "Roar \"Strange Roar\""s,
    "Roar \"Full Moon Howling\""s,
    "Roar \"Full Moon Howling\""s,
    "Wolf Sign \"Star Ring Pounce\""s,
    "Wolf Sign \"Star Ring Pounce\""s,
    "Sirius \"High-Speed Pounce\""s,
    "Sirius \"High-Speed Pounce\""s,
    // stage 4 (41-64) (24 cards)
    "Heikyoku \"Sounds of Jetavana's Bell\""s,
    "Heikyoku \"Sounds of Jetavana's Bell\""s,
    "Heikyoku \"Sounds of Jetavana's Bell\""s,
    "Heikyoku \"Sounds of Jetavana's Bell\""s,
    "Vengeful Spirit \"Hoichi the Earless\""s,
    "Vengeful Spirit \"Hoichi the Earless\""s,
    "Vengeful Spirit \"Great Vengeful Spirit of Taira\""s,
    "Vengeful Spirit \"Great Vengeful Spirit of Taira\""s,
    "Music Sign \"Wicked Musical Score\""s,
    "Music Sign \"Wicked Musical Score\""s,
    "Music Sign \"Malicious Musical Score\""s,
    "Music Sign \"Double Score\""s,
    "Koto Sign \"Sounds of Anicca's Koto\""s,
    "Koto Sign \"Sounds of Anicca's Koto\""s,
    "Koto Sign \"Sounds of Anicca's Koto\""s,
    "Koto Sign \"Sounds of Anicca's Koto\""s,
    "Echo Sign \"Heian's Reverberation\""s,
    "Echo Sign \"Heian's Reverberation\""s,
    "Echo Sign \"Echo Chamber\""s,
    "Echo Sign \"Echo Chamber\""s,
    "Koto Music \"Social Upheaval Koto Dirge\""s,
    "Koto Music \"Social Upheaval Koto Dirge\""s,
    "Koto Music \"Social Upheaval Requiem\""s,
    "Koto Music \"Social Upheaval Requiem\""s,
    // stage 5 (65-84) (20 cards)
    "Deceit Sign \"Reverse Needle Attack\""s,
    "Deceit Sign \"Reverse Needle Attack\""s,
    "Deceit Sign \"Reverse Needle Attack\""s,
    "Deceit Sign \"Reverse Needle Attack\""s,
    "Reverse Sign \"Danmaku Through the Looking-Glass\""s,
    "Reverse Sign \"Danmaku Through the Looking-Glass\""s,
    "Reverse Sign \"Evil in the Mirror\""s,
    "Reverse Sign \"Evil in the Mirror\""s,
    "Reverse Sign \"This Side Down\""s,
    "Reverse Sign \"This Side Down\""s,
    "Reverse Sign \"Overturning All Under Heaven\""s,
    "Reverse Sign \"Overturning All Under Heaven\""s,
    "Reverse Bow \"Dream Bow of Heaven & Earth\""s,
    "Reverse Bow \"Dream Bow of Heaven & Earth\""s,
    "Reverse Bow \"Decree of the Dream Bow of Heaven & Earth\""s,
    "Reverse Bow \"Decree of the Dream Bow of Heaven & Earth\""s,
    "Turnabout \"Reverse Hierarchy\""s,
    "Turnabout \"Reverse Hierarchy\""s,
    "Turnabout \"Change Air Brave\""s,
    "Turnabout \"Change Air Brave\""s,
    // stage 6 (85-108) (24 cards)
    "Small Bullet \"Inchling's Path\""s,
    "Small Bullet \"Inchling's Path\""s,
    "Small Bullet \"Inchling's Thorny Path\""s,
    "Small Bullet \"Inchling's Thorny Path\""s,
    "Mallet \"Grow Bigger!\""s,
    "Mallet \"Grow Bigger!\""s,
    "Mallet \"Grow Even Bigger!\""s,
    "Mallet \"Grow Even Bigger!\""s,
    "Bewitched Sword \"Shining Needle Sword\""s,
    "Bewitched Sword \"Shining Needle Sword\""s,
    "Bewitched Sword \"Shining Needle Sword\""s,
    "Bewitched Sword \"Shining Needle Sword\""s,
    "Mallet \"You Grow Bigger!\""s,
    "Mallet \"You Grow Bigger!\""s,
    "Mallet \"You Grow Bigger!\""s,
    "Mallet \"You Grow Bigger!\""s,
    "\"Attack on Dwarf\""s,
    "\"Attack on Dwarf\""s,
    "\"Wall of Issun\""s,
    "\"Wall of Issun\""s,
    "\"Hop-o'-My-Thumb Seven\""s,
    "\"Hop-o'-My-Thumb Seven\""s,
    "\"The Seven Issun-Boushi\""s,
    "\"The Seven Issun-Boushi\""s,
    // extra stage (109-120) (12 cards)
    "String Music \"Storm Ensemble\""s,
    "String Music \"Joururi World\""s,
    "First Drum \"Raging Temple Taiko\""s,
    "Second Drum \"Vengeful Spirit Aya-no-Tsuzumi\""s,
    "Third Drum \"Three Strikes at Midnight\""s,
    "Death Drum \"Land Percuss\""s,
    "Fifth Drum \"Den-Den Daiko\""s,
    "Sixth Drum \"Alternate Sticking\""s,
    "Seventh Drum \"High Speed Taiko Rocket\""s,
    "Eighth Drum \"Thunder God's Anger\""s,
    "\"Blue Lady Show\""s,
    "\"Pristine Beat\""s,
};

// Touhou 14 Music
export const vector<string> th14_musicNames = {
    "unused"s,
    "Mysterious Purification Rod"s,
    "Mist Lake"s,
    "Mermaid from the Uncharted Land"s,
    "Humans and Youkai Traversing the Canal"s,
    "Dullahan Under the Willows"s,
    "Bamboo Forest of the Full Moon"s,
    "Lonesome Werewolf"s,
    "unused"s,
    "Magical Storm"s,
    "Illusionary Joururi"s,
    "The Shining Needle Castle Sinking in the Air"s,
    "Reverse Ideology"s,
    "unused"s,
    "The Exaggerated Castle Keep"s,
    "Inchlings of the Shining Needle ~ Little Princess"s,
    "Magical Power of the Mallet"s,
    "Mysterious, Mysterious Tools"s,
    "Thunderclouds of Magical Power"s,
    "Primordial Beat ~ Pristine Beat"s,
};

// Touhou 14.3 stage names
export const vector<string> th143_stageNames = {
    "unused"s,
    // Day 1
    "Cheat Against Impossible Danmaku"s,
    "Unavoidable Tailfin"s,
    "Violent Freeze"s,
    "Encroaching Terror"s,
    "Gee Cirno, You Sure Are Conceited"s,
    "Persistent School of Fish"s,
    // Day 2
    "Youkai at the Gate, Reading An Unlearnable Sutra"s,
    "Longest-Necked Kayan in the World"s,
    "An Ear-Piercing Scream"s,
    "Do Beams or Romance Come From Her Eyes?"s,
    "Neverending Sutra Book"s,
    "Two-Headed Dragon"s,
    // Day 3
    "Multiplying Pursuers"s,
    "Dangers Abound on a Full Moon"s,
    "A Tranquil Dystopia"s,
    "Oh, If Only the Screen Had No Edges"s,
    "Do I Smell?"s,
    "The Array of Edo's Fight"s,
    "Even Immortals Get Tired"s,
    // Day 4
    "What Appears at the Graveyard"s,
    "A Rather Suspicious Vitality"s,
    "Evaporating Butterflies"s,
    "Get Hit, and You're Zombified"s,
    "Walls Closing In"s,
    "Will you Dodge it, Erase it, or...?"s,
    "Enemies have Freedom Too"s,
    // Day 5
    "Can't Just Rely On Items Alone"s,
    "Stop Aiming At Me!"s,
    "Intertwined Melody"s,
    "If I Could Just Break Those Stupid Drums..."s,
    "Requiem"s,
    "Silent Score"s,
    "Super-Heavy Bass"s,
    "Must we Avoid this Beautiful Night?"s,
    // Day 6
    "The Big includes the Small"s,
    "The Camera is Mightier than the Pen"s,
    "The Latest Cellphone Camera"s,
    "Unreliable Waterfalls"s,
    "Bite a Lot to Train Your Jaw"s,
    "Drowning Gun With a Shady Story"s,
    "An Overblown Article Written by a Shut-In"s,
    "Don't Give Her a Photo Op"s,
    // Day 7
    "The Big includes the Small"s,
    "I Don't Know What Happened"s,
    "Cut the Flesh, Sever the Bone"s,
    "Systematic Reptile"s,
    "Firing Indiscriminately"s,
    "Don't You Think That's Devious?"s,
    "She's Also Firing Indiscriminately"s,
    "There's No Venom in a Common Snake"s,
    // Day 8
    "Turn Everyone into an Enemy!"s,
    "The Perfect Entrapment"s,
    "You Can't Rely On Items Alone"s,
    "Teeeensy Danmaku"s,
    "Normal Shots Are Scary, Huh?"s,
    "They're Nice, Compared to the Others"s,
    "Amanojaku Aren't Necessarily Oni"s,
    // Day 9
    "Yaaay, Rising!"s,
    "Itoigawa is Known for Its Jade"s,
    "Sometimes a Boatman Must Climb a Mountain"s,
    "So the Tiny Ones Are Real Too?"s,
    "One Should Fear Angering the Gods"s,
    "My Precious Amphibians...!"s,
    "Double Dragon"s,
    "Desperate to Gather Rumors"s,
    // Day 10
    "The Fourth Monster appears"s,
    "Did You Plan on Becoming God?"s,
    "So You Got Youkai Piled Up, Too"s,
    "12-Second Nightmare"s,
    "Cheating Back at You...!"s,
    "Round 'n' Round 'n' Round"s,
    "Teacher, I Don't Want to Study History Anymore"s,
    "Pickling Stone Drill"s,
    "I Got You... Huh!?"s,
    "You Just Have to Persevere"s,
};

// Touhou 14.3 Bosses and Spells
export const vector<string> th143_bossAndSpells = {
    "unused"s,
    // Day 1
    "Yatsuhashi Tsukumo"s,
    "Wakasagihime - Water Sign \"Lunatic Red Slap\""s,
    "Cirno - Ice Sign \"Perfect Glacialist\""s,
    "Wakasagihime - Tide Sign \"Tidal Wave of the Lake\""s,
    "Cirno - Ice King \"Frost King\""s,
    "Wakasagihime - Fish Sign \"School of Fish\""s,
    // Day 2
    "Kyouko Kasodani - Scream \"Primal Scream\""s,
    "Sekibanki - Flying Neck \"Extreme Long Neck\""s,
    "Kyouko Kasodani - Piercing Sound \"Piercing Circle\""s,
    "Sekibanki - Glinting Eyes \"Hell's Ray\""s,
    "Kyouko Kasodani - Sutra \"Infinite Nenbutsu\""s,
    "Sekibanki - Flying Neck \"Twin Rokuro Head\""s,
    // Day 3
    "Kagerou Imaizumi"s,
    "Kagerou Imaizumi - Full Moon \"Full Moon Roar\""s,
    "Keine Kamishirasawa - \"20XX: An Afterlife Odyssey\""s,
    "Fujiwara no Mokou - Regretful Life \"Immortality's Reckless Sacrifice\""s,
    "Kagerou Imaizumi - Wolf Fang \"Bloodthirsty Wolf Fang\""s,
    "Keine Kamishirasawa - Great Fire \"Flower of Edo\""s,
    "Fujiwara no Mokou - \"Fire Bird -Legend of Immortality-\" || \"Resurrection\""s,
    // Day 4
    "Yuyuko Saigyouji"s,
    "Seiga Kaku - Demonify \"Excessive Zouhuo Rumo\""s,
    "Yuyuko Saigyouji - Butterfly Sign \"Flower, Butterfly, Wind, and Moon\""s,
    "Yoshika Miyako - Poison Nail \"Zombie Claw\""s,
    "Seiga Kaku - Hermit Arts \"Wall Runner\""s,
    "Yuyuko Saigyouji - Cherry Blossom \"Lovely Cherry Blossom Blizzard\""s,
    "Seiga Kaku - Hermit Arts \"Wall - Phasing Wormhole\""s,
    // Day 5
    "Raiko Horikawa"s,
    "Yatsuhashi Tsukumo - Koto Sign \"Ame no Norigoto\""s,
    "Benben Tsukumo - Noise Sign \"Biwa of Euphoric Song\""s,
    "Raiko Horikawa - Thunder Sign \"Den-Den Daiko of Rage\""s,
    "Yatsuhashi Tsukumo - Elegy \"Human & Koto Die Together\""s,
    "Benben Tsukumo - Score \"Score Web\""s,
    "Raiko Horikawa - Taiko \"Fantastic Woofer\""s,
    "Benben and Yatsuhashi Tsukumo - Double Chant \"Song of Falling Stars\""s,
    // Day 6
    "Mamizou Futatsuiwa"s,
    "Aya Shameimaru - Photography \"Quick-Shooting Tengu Scoop\""s,
    "Hatate Himekaidou - Photography \"Full Panoramic Shot\""s,
    "Nitori Kawashiro - Waterfall Sign \"Shiraito Falls\""s,
    "Momiji Inubashiri - Fang Sign \"Chewing Satisfaction\""s,
    "Nitori Kawashiro - Waterfall Sign \"Kegon Gun\""s,
    "Hatate Himekaidou - Photography \"Secluded Paparazzi\""s,
    "Aya Shameimaru - \"Instant Shot Journalist\""s,
    // Day 7
    "Marisa Kirisame - Love Sign \"Wide Master\""s,
    "Sakuya Izayoi - Time Sign \"Time Stopper Sakuya\""s,
    "Youmu Konpaku - Light Sign \"Light Flash of the Netherworld\""s,
    "Sanae Kochiya - Snake Sign \"Bind Snake Come On\""s,
    "Marisa Kirisame - Love Sign \"Machine Gun Spark\""s,
    "Sakuya Izayoi - Time Sign \"Changeling Magic\""s,
    "Youmu Konpaku - Higan Sword \"Hacking Slashes of Hell & Paradise\""s,
    "Sanae Kochiya - Snake Sign \"Green Snake Come On\""s,
    // Day 8
    "Shinmyoumaru Sukuna"s,
    "Reimu Hakurei - Mikuji \"Rule Violation Barrier\""s,
    "Mamizou Futatsuiwa - \"If the Cuckoo Does Not Sing, Wait For It to Cry\""s,
    "Shinmyoumaru Sukuna - \"Inchlings' Hell\""s,
    "Reimu Hakurei - \"Persuasion Needle\""s,
    "Mamizou Futatsuiwa - \"Humans Are Nice!\""s,
    "Shinmyoumaru Sukuna - Shining Needle \"Oni-Slaying, Eye-Stabbing Needle\""s,
    // Day 9
    "Kanako Yasaka - Onbashira \"Rising Onbashira\""s,
    "Suwako Moriya - Green Stone \"Jade Break\""s,
    "Mononobe no Futo - Old Boat \"Ancient Ship\""s,
    "Suika Ibuki - Oni Crowd \"Imp Swarm\""s,
    "Kanako Yasaka - \"Sacred Authority of the Gods\""s,
    "Suwako Moriya - Frog Sign \"Bloody Mound of Red Frogs\""s,
    "Mononobe no Futo - Heat Dragon \"Blazing Dragon Veins\""s,
    "Suika Ibuki - Oni Crowd \"Hundred Oni Kaburo\""s,
    // Day 10
    "Byakuren Hijiri - \"Binding Laws of Hari\""s,
    "Toyosatomimi no Miko - \"My Way is Truly That of Heaven!\""s,
    "Tenshi Hinanawi - \"Sky of Scarlet Perception of All Youkaikind\""s,
    "Remilia Scarlet - \"Fitful Nightmare\""s,
    "Yukari Yakumo - \"Impossible Danmaku Barrier\""s,
    "Byakuren Hijiri - \"Eyes of Brahma\""s,
    "Toyosatomimi no Miko - \"Seventeen-Article Constitution Bombs\""s,
    "Tenshi Hinanawi - \"Kashima Protection\""s,
    "Remilia Scarlet - \"Duck, Duck, Bat!\""s,
    "Yukari Yakumo - \"Casebook of Luck, Resilience, and Perseverance\""s,
};

// Touhou 14.3 Music
export const vector<string> th143_musicNames = {
    "Raise the Signal Fire of Cheating"s,
    "Cheat Against the Impossible Danmaku"s,
    "Midnight Spell Card"s,
    "Romantic Escape Flight"s,
    "Eternal Transient Reign"s,
    "Mermaid from the Uncharted Land"s,
    "Reverse Ideology"s,
    "Illusionary Joururi"s,
    "Youkai Mountain ~ Mysterious Mountain"s,
};

// Touhou 15 Music
export const vector<string> th15_musicNames = {
    "unused"s,
    "The Space Shrine Maiden Appears"s,
    "Unforgettable, the Nostalgic Greenery"s,
    "The Lake Reflects the Cleansed Moonlight"s,
    "The Rabbit Has Landed"s,
    "September Pumpkin"s,
    "The Mysterious Shrine Maiden Flying Through Space"s,
    "Eternal Spring Dream"s,
    "The Frozen Eternal Capital"s,
    "Reversed Wheel of Fortune"s,
    "Faraway Voyage of 380,000 Kilometers"s,
    "Pierrot of the Star-Spangled Banner"s,
    "The Sea that Reflects One's Home Planet"s,
    "Pure Furies ~ Whereabouts of the Heart"s,
    "The Moon as Seen from the Shrine"s,
    "The Space Shrine Maiden Returns Home"s,
    "A World of Nightmares Never Seen Before"s,
    "Pandemonic Planet"s,
};

// Touhou 16
export const vector<string> th16_spellCardName = {
    // stage 1 (8 cards)
    "Butterfly Sign \"Minute Scales\""s,
    "Butterfly Sign \"Minute Scales\""s,
    "Butterfly Sign \"Swallowtail's Scales\""s,
    "Butterfly Sign \"Swallowtail's Scales\""s,
    "Butterfly Sign \"Fluttering Summer\""s,
    "Butterfly Sign \"Fluttering Summer\""s,
    "Butterfly Sign \"Midsummer Wingbeats\""s,
    "Butterfly Sign \"Midsummer Wingbeats\""s,
    // stage 2 (12 cards)
    "Rain Sign \"Imprisoning Autumn Rain\""s,
    "Rain Sign \"Imprisoning Autumn Rain\""s,
    "Rain Sign \"Cursed Torrential Rain\""s,
    "Rain Sign \"Cursed Torrential Rain\""s,
    "Blade Sign \"Yamanba's Kitchen Knife Sharpening\""s,
    "Blade Sign \"Yamanba's Kitchen Knife Sharpening\""s,
    "Blade Sign \"Yamanba's Oni Kitchen Knife Sharpening\""s,
    "Blade Sign \"Yamanba's Oni Kitchen Knife Sharpening\""s,
    "Blade Exhaustion Sign \"Mountain Murder\""s,
    "Blade Exhaustion Sign \"Mountain Murder\""s,
    "Blade Exhaustion Sign \"Bloody Mountain Murder\""s,
    "Blade Exhaustion Sign \"Bloody Mountain Murder\""s,
    // stage 3 (14 cards)
    "Spring Sign \"Surprise Spring\""s,
    "Spring Sign \"Surprise Spring\""s,
    "Dog Sign \"Stray Dog's Walk\""s,
    "Dog Sign \"Stray Dog's Walk\""s,
    "Hound Sign \"Mountain Hound's Walk\""s,
    "Hound Sign \"Mountain Hound's Walk\""s,
    "Spinning Top \"Koma-Inu Spin\""s,
    "Spinning Top \"Koma-Inu Spin\""s,
    "Spinning Top \"Koma-Inu Spin\""s,
    "Spinning Top \"Curl Up And Die\""s,
    "Koma Sign \"Solitary A-Un Breathing\""s,
    "Koma Sign \"Solitary A-Un Breathing\""s,
    "Koma Sign \"Solitary A-Un Breathing\""s,
    "Koma Sign \"Solitary A-Un Breathing\""s,
    // stage 4 (12 cards)
    "Magic Sign \"Instant Bodhi\""s,
    "Magic Sign \"Instant Bodhi\""s,
    "Magic Sign \"Bodhi in an Instant\""s,
    "Magic Sign \"Bodhi in an Instant\""s,
    "Magic Sign \"Bullet Golem\""s,
    "Magic Sign \"Bullet Golem\""s,
    "Magic Sign \"Gigantic Pet Bullet Lifeform\""s,
    "Magic Sign \"Gigantic Pet Bullet Lifeform\""s,
    "Jizo \"Criminal Salvation\""s,
    "Jizo \"Criminal Salvation\""s,
    "Jizo \"Hellfire Salvation\""s,
    "Jizo \"Hellfire Salvation\""s,
    // stage 5 (24 cards)
    "Bamboo Sign \"Bamboo Spear Dance\""s,
    "Bamboo Sign \"Bamboo Spear Dance\""s,
    "Bamboo Sign \"Bamboo Crazy Dance\""s,
    "Bamboo Sign \"Bamboo Crazy Dance\""s,
    "Myoga Ginger \"Forget Your Name\""s,
    "Myoga Ginger \"Forget Your Name\""s,
    "Myoga Ginger \"Forget Your Name\""s,
    "Myoga Ginger \"Forget Your Name\""s,
    "Broadleaf Sign \"Tanabata Star Festival\""s,
    "Broadleaf Sign \"Tanabata Star Festival\""s,
    "Broadleaf Sign \"Tanabata Star Festival\""s,
    "Broadleaf Sign \"Tanabata Star Festival\""s,
    "Myoga Blessing \"Behind You\""s,
    "Myoga Blessing \"Behind You\""s,
    "Myoga Blessing \"Behind You\""s,
    "Myoga Blessing \"Behind You\""s,
    "Dance Sign \"Behind Festival\""s,
    "Dance Sign \"Behind Festival\""s,
    "Dance Sign \"Behind Festival\""s,
    "Dance Sign \"Behind Festival\""s,
    "Mad Dance \"Tengu-Odoshi\""s,
    "Mad Dance \"Tengu-Odoshi\""s,
    "Mad Dance \"Frenzied Tengu-Frightening\""s,
    "Mad Dance \"Frenzied Tengu-Frightening\""s,
    // stage 6 (36 cards, 16 of which are season finals damn I hate it)
    "Back Sign \"Halo of the Secret God\""s,
    "Back Sign \"Halo of the Secret God\""s,
    "Back Sign \"Halo of the Secret God\""s,
    "Back Sign \"Halo of the Absolute Secret God\""s,
    "Hidden Summer \"Scorch by Hot Summer\""s,
    "Hidden Summer \"Scorch by Hot Summer\""s,
    "Hidden Summer \"Scorched Earth of Abnormal Intense Heat\""s,
    "Hidden Summer \"Scorched Earth of Abnormal Intense Heat\""s,
    "Hidden Fall \"Die of Famine\""s,
    "Hidden Fall \"Die of Famine\""s,
    "Hidden Fall \"Preta of Abnormal Blight\""s,
    "Hidden Fall \"Preta of Abnormal Blight\""s,
    "Hidden Winter \"Black Snowman\""s,
    "Hidden Winter \"Black Snowman\""s,
    "Hidden Winter \"Snowman of Abnormal Snowfall\""s,
    "Hidden Winter \"Snowman of Abnormal Snowfall\""s,
    "Hidden Spring \"April Wizard\""s,
    "Hidden Spring \"April Wizard\""s,
    "Hidden Spring \"Black Magician of Abnormal Falling Petals\""s,
    "Hidden Spring \"Black Magician of Abnormal Falling Petals\""s,
    "\"Hidden Breezy Cherry Blossom\""s,
    "\"Hidden Breezy Cherry Blossom\""s,
    "\"Hidden Breezy Cherry Blossom\""s,
    "\"Hidden Breezy Cherry Blossom\""s,
    "\"Hidden Perfect Summer Ice\""s,
    "\"Hidden Perfect Summer Ice\""s,
    "\"Hidden Perfect Summer Ice\""s,
    "\"Hidden Perfect Summer Ice\""s,
    "\"Hidden Crazy Fall Wind\""s,
    "\"Hidden Crazy Fall Wind\""s,
    "\"Hidden Crazy Fall Wind\""s,
    "\"Hidden Crazy Fall Wind\""s,
    "\"Hidden Extreme Winter\""s,
    "\"Hidden Extreme Winter\""s,
    "\"Hidden Extreme Winter\""s,
    "\"Hidden Extreme Winter\""s,
    // extra stage (13 cards)
    "Drum Dance \"Powerful Cheers\""s,
    "Mad Dance \"Crazy Backup Dance\""s,
    "Bullet Dance \"Two-Eyed Typhoon\""s,
    "Secret Ceremony \"Reverse Invoker\""s,
    "Secret Ceremony \"Rear Shots of Betrayal\""s,
    "Secret Ceremony \"Danmaku Dupion\""s,
    "Secret Ceremony \"Fire of Ena\""s,
    "Secret Ceremony \"Kyogen of the Back Door\""s,
    "Secret Ceremony \"Matarah Dukkha\""s,
    "Secret Ceremony \"Sword of the Seven Stars\""s,
    "Secret Ceremony \"Performers Unattached to Society\""s,
    "\"The Back Face's Dark Sarugaku\""s,
    "\"Anarchy Bullet Hell\""
};

// Touhou 16 Music
export const vector<string> th16_musicNames = {
    "unused"s,
    "The Sky Where Cherry Blossoms Flutter Down"s,
    "A Star of Hope Rises in the Blue Sky"s,
    "A Midsummer Fairy's Dream"s,
    "The Colorless Wind on Youkai Mountain"s,
    "Deep-Mountain Encounter"s,
    "Swim in a Cherry Blossom-Colored Sea"s,
    "A Pair of Divine Beasts"s,
    "Illusionary White Traveler"s,
    "The Magic Straw-Hat Jizo"s,
    "Does the Forbidden Door Lead to This World, or the World Beyond?"s,
    "Crazy Backup Dancers"s,
    "The Concealed Four Seasons"s,
    "Into Backdoor"s,
    "Unnatural Nature"s,
    "White Traveler"s,
    "No More Going Through Doors"s,
    "Secret God Matara ~ Hidden Star in All Seasons."s,
};

// Touhou 17
export const vector<string> th17_spellCardName = {
    // stage 1 (1-8, 8 cards)
    "Stone Sign \"Stone Woods\""s,
    "Stone Sign \"Stone Woods\""s,
    "Stone Sign \"Stone Conifers\""s,
    "Stone Sign \"Stone Conifers\""s,
    "Stone Sign \"Children's Limbo\""s,
    "Stone Sign \"Children's Limbo\""s,
    "Stone Sign \"Adult Children's Limbo\""s,
    "Stone Sign \"Adult Children's Limbo\""s,
    // stage 2 (9-20, 12 cards)
    "Stone Sign \"Stone Baby\""s,
    "Stone Sign \"Stone Baby\""s,
    "Stone Sign \"Heavy Stone Baby\""s,
    "Stone Sign \"Heavy Stone Baby\""s,
    "Drowning Sign \"Drowning in the Sanzu\""s,
    "Drowning Sign \"Drowning in the Sanzu\""s,
    "Drowning Sign \"Drowning in the Sanzu\""s,
    "Drowning Sign \"Drowning in the Sanzu\""s,
    "Oni Sign \"Demon Siege\""s,
    "Oni Sign \"Demon Siege\""s,
    "Oni Sign \"Hungry Demon Siege\""s,
    "Oni Sign \"Hungry Demon Siege\""s,
    // stage 3 (21-32, 12 cards)
    "Water Sign \"Ordeal of Water Distribution\""s,
    "Water Sign \"Ordeal of Water Distribution\""s,
    "Water Sign \"High-Level Purgatordeal of Water Distribution\""s,
    "Water Sign \"Ultimate Purgatordeal of Water Distribution\""s,
    "Light Sign \"Ordeal of Surveying\""s,
    "Light Sign \"Ordeal of Surveying\""s,
    "Light Sign \"High-Level Purgatordeal of Surveying\""s,
    "Light Sign \"Ultimate Purgatordeal of Surveying\""s,
    "Oni Sign \"Purgatordeal of Oniwatari\""s,
    "Oni Sign \"Purgatordeal of Oniwatari\""s,
    "Oni Sign \"High-Level Purgatordeal of Oniwatari\""s,
    "Oni Sign \"Hell-Level Purgatordeal of Oniwatari\""s,
    // stage 4 (33-44, 12 cards)
    "Tortoise Sign \"Tortoiseshell Hell\""s,
    "Tortoise Sign \"Tortoiseshell Hell\""s,
    "Tortoise Sign \"Tortoiseshell Hell\""s,
    "Tortoise Sign \"Tortoiseshell Hell\""s,
    "Oni Sign \"Beasts Attacking from the Rear\""s,
    "Oni Sign \"Beasts Attacking from the Rear\""s,
    "Oni Sign \"Mangy Beasts Attacking from the Rear\""s,
    "Oni Sign \"Devilish Beasts Attacking from the Rear\""s,
    "Dragon Sign \"Dragon Crest Bullets\""s,
    "Dragon Sign \"Dragon Crest Bullets\""s,
    "Dragon Sign \"Dragon Crest Bullets\""s,
    "Dragon Sign \"Dragon Crest Bullets\""s,
    // stage 5 (45-60, 16 cards)
    "Haniwa \"Archer Haniwa\""s,
    "Haniwa \"Archer Haniwa\""s,
    "Haniwa \"Skilled Archer Haniwa\""s,
    "Haniwa \"Skilled Archer Haniwa\""s,
    "Haniwa \"Fencer Haniwa\""s,
    "Haniwa \"Fencer Haniwa\""s,
    "Haniwa \"Skilled Fencer Haniwa\""s,
    "Haniwa \"Skilled Fencer Haniwa\""s,
    "Haniwa \"Cavalry Haniwa\""s,
    "Haniwa \"Cavalry Haniwa\""s,
    "Haniwa \"Skilled Cavalry Haniwa\""s,
    "Haniwa \"Skilled Cavalry Haniwa\""s,
    "Haniwa \"Hollow Inexhaustible Troops\""s,
    "Haniwa \"Hollow Inexhaustible Troops\""s,
    "Haniwa \"Undefeated Inexhaustible Troops\""s,
    "Haniwa \"Undefeated Inexhaustible Troops\""s,
    // stage 6 (61-88, 28 cards)
    "Square Shape \"Square-Shaped Sculpting Art\""s,
    "Square Shape \"Square-Shaped Sculpting Art\""s,
    "Square Shape \"Square Creature\""s,
    "Square Shape \"Square Creature\""s,
    "Circular Shape \"Perfect Circle Sculpting Art\""s,
    "Circular Shape \"Perfect Circle Sculpting Art\""s,
    "Circular Shape \"Circle Creature\""s,
    "Circular Shape \"Circle Creature\""s,
    "Linear Shape \"Line-Shaped Sculpting Art\""s,
    "Linear Shape \"Line-Shaped Sculpting Art\""s,
    "Linear Shape \"Linear Creature\""s,
    "Linear Shape \"Linear Creature\""s,
    "Haniwa \"Horse-and-Rider Idol Sculpting Art\""s,
    "Haniwa \"Horse-and-Rider Idol Sculpting Art\""s,
    "Haniwa \"Idol Creature\""s,
    "Haniwa \"Idol Creature\""s,
    "\"Oni-Shaped Sculpting Art\""s,
    "\"Oni-Shaped Sculpting Art\""s,
    "\"Oni-Shaped Sculpting Art\""s,
    "\"Oni-Shaped Sculpting Art\""s,
    "\"Geometric Creature\""s,
    "\"Geometric Creature\""s,
    "\"Geometric Creature\""s,
    "\"Geometric Creature\""s,
    "\"Idola Diabolus\""s,
    "\"Idola Diabolus\""s,
    "\"Idola Diabolus\""s,
    "\"Idola Diabolus\""s,
    // extra stage (89-101, 13 cards)
    "Bloody Battle \"Watershed of Blood\""s,
    "Bloody Battle \"Hell Realm Sight-Line\""s,
    "Bloody Battle \"All-Spirit Oniwatari\""s,
    "Agile Skill \"Thrilling Shot\""s,
    "Agile Skill \"Lightning Neigh\""s,
    "Agile Skill \"Dense Crowd\""s,
    "Agile Skill \"Beast Epidemicity\""s,
    "Agile Skill \"Triangle Chase\""s,
    "Agile Skill \"Black Pegasus Meteor Shot\""s,
    "Agile Skill \"Muscle Explosion\""s,
    "\"Follow Me, Unafraid\""s,
    "\"Oni-Shaped Hoi Polloi\""s,
    "\"Deeds of Devilish Beasts\""s,
};

// Touhou 17 Music
export const vector<string> th17_musicNames = {
    "unused"s,
    "Silent Beast Spirits"s,
    "unused"s,
    "The Lamentations Known Only to Jizo"s,
    "Jelly Stone"s,
    "Lost River"s,
    "The Stone Baby and the Submerged Bovine"s,
    "Everlasting Red Spider Lily"s,
    "Seraphic Chicken"s,
    "Unlocated Hell"s,
    "Tortoise Dragon ~ Fortune and Misfortune"s,
    "Beast Metropolis"s,
    "Joutoujin of Ceramics"s,
    "Entrust the World to Idols ~ Idolatrize World"s,
    "Electric Heritage"s,
    "The Animals' Rest"s,
    "Return from the Underground"s,
    "The Shining Law of the Strong Eating the Weak"s,
    "Prince Shoutoku's Pegasus ~ Dark Pegasus"s,
};

// Touhou 18
export const vector<string> th18_spellCardName = {
    // stage 1 (1-8, 8 cards)
    "Beckon Sign \"Many Danmaku Guests\""s,
    "Beckon Sign \"Many Danmaku Guests\""s,
    "Beckon Sign \"Many Danmaku Guests\""s,
    "Beckon Sign \"Many Danmaku Guests\""s,
    "Beckon Sign \"Shoot Away Disaster, Beckon in Fortune\""s,
    "Beckon Sign \"Shoot Away Disaster, Beckon in Fortune\""s,
    "Beckon Sign \"Shoot Away Disaster, Beckon in Fortune\""s,
    "Beckon Sign \"Shoot Away Disaster, Beckon in Fortune\""s,
    // stage 2 (9-20, 12 cards)
    "Forest Sign \"Tree-Veiling Technology\""s,
    "Forest Sign \"Tree-Veiling Technology\""s,
    "Forest Sign \"Extreme Tree-Veiling Technology\""s,
    "Forest Sign \"True Tree-Veiling Technology\""s,
    "Forest Sign \"Innermost Forest Region\""s,
    "Forest Sign \"Innermost Forest Region\""s,
    "Forest Sign \"Extreme Innermost Forest Region\""s,
    "Forest Sign \"True Innermost Forest Region\""s,
    "Leaf Skill \"Green Spiral\""s,
    "Leaf Skill \"Green Spiral\""s,
    "Leaf Skill \"Green Cyclone\""s,
    "Leaf Skill \"Green Tornado\""s,
    // stage 3 (21-32, 12 cards)
    "Mountain Sign \"Heaven-Shaking Kumomagusa\""s,
    "Mountain Sign \"Heaven-Shaking Kumomagusa\""s,
    "Mountain Apparition \"Astonishing Kumomagusa\""s,
    "Mountain Apparition \"Astonishing Kumomagusa\""s,
    "Mountain Sign \"Usuyukisou Shining with Bewitching Light\""s,
    "Mountain Sign \"Usuyukisou Shining with Bewitching Light\""s,
    "Mountain Apparition \"Usuyukisou of Thronging Crowds of Youma\""s,
    "Mountain Apparition \"Usuyukisou of Thronging Crowds of Youma\""s,
    "Mountain Flower \"Komakusa of Massacre\""s,
    "Mountain Flower \"Komakusa of Massacre\""s,
    "Mountain Flower \"Mountain Queen of Massacre\""s,
    "Mountain Flower \"Mountain Queen of Massacre\""s,
    // stage 4 (33-44, 12 cards)
    "Orb Sign \"Rainbow Dragon Yin-Yang Orbs\""s,
    "Orb Sign \"Rainbow Dragon Yin-Yang Orbs\""s,
    "Orb Sign \"Rainbow Dragon Yin-Yang Orbs\""s,
    "Orb Sign \"Yin-Yang Divine Orbs\""s,
    "Jeweled General \"Queen of Yin-Yang Sphere\""s,
    "Jeweled General \"Queen of Yin-Yang Sphere\""s,
    "Queenly Gem \"Beyond the Rainbow Door\""s,
    "Queenly Gem \"Beyond the Rainbow Door\""s,
    "\"Yin-Yang Suffocation\""s,
    "\"Yin-Yang Suffocation\""s,
    "\"Yin-Yang Suffocation\""s,
    "\"Yin-Yang Suffocation\""s,
    // stage 5 (45-60, 16 cards)
    "Calamitous Star \"Dance of the Wildfire Started by a Star's Spark\""s,
    "Calamitous Star \"Dance of the Wildfire Started by a Star's Spark\""s,
    "Calamitous Star \"Wild Dance of the Wildfire Started by a Star's Spark\""s,
    "Calamitous Star \"Wild Dance of the Wildfire Started by a Star's Spark\""s,
    "Stellar Wind \"Dance of Dazzling Iridescence\""s,
    "Stellar Wind \"Dance of Dazzling Iridescence\""s,
    "Stellar Wind \"Wild Dance of Dazzling Iridescence\""s,
    "Stellar Wind \"Wild Dance of Dazzling Iridescence\""s,
    "Luminous Horse \"Dance of Sky-Racing Heavenly Steeds\""s,
    "Luminous Horse \"Dance of Sky-Racing Heavenly Steeds\""s,
    "Luminous Horse \"Wild Dance of Sky-Racing Heavenly Steeds\""s,
    "Luminous Horse \"Wild Dance of Sky-Racing Heavenly Steeds\""s,
    "Rainbow Illumination \"Clear and Tranquil Wind and Moon\""s,
    "Rainbow Illumination \"Clear and Tranquil Wind and Moon\""s,
    "Rainbow Illumination \"Clear and Tranquil Wind and Moon\""s,
    "Rainbow Illumination \"Clear and Tranquil Wind and Moon\""s,
    // stage 6 (61-84, 24 cards)
    "\"An Offering to the Ownerless\""s,
    "\"An Offering to the Ownerless\""s,
    "\"An Offering to the Ownerless\""s,
    "\"An Offering to the Ownerless\""s,
    "\"Danmaku Hoarder's Obsession\""s,
    "\"Danmaku Hoarder's Obsession\""s,
    "\"Danmaku Hoarder's Obsession\""s,
    "\"Danmaku Hoarder's Obsession\""s,
    "\"Bullet Market\""s,
    "\"Bullet Market\""s,
    "\"High-Density Bullet Market\""s,
    "\"Danmaku Free Market\""s,
    "\"Rainbow Ring of People\""s,
    "\"Rainbow Ring of People\""s,
    "\"Rainbow Ring of People\""s,
    "\"Rainbow Ring of People\""s,
    "\"Bullet Dominion\""s,
    "\"Bullet Dominion\""s,
    "\"Tyrannical Bullet Dominion\""s,
    "\"Inhumane Bullet Dominion\""s,
    "\"Asylum of Danmaku\""s,
    "\"Asylum of Danmaku\""s,
    "\"Asylum of Danmaku\""s,
    "\"Asylum of Danmaku\""s,
    // extra stage (85-97, 13 cards)
    "Fox Sign \"Fox Winder\""s,
    "Kuda-gitsune \"Cylinder Fox\""s,
    "Stellar Fox \"Dance of Heavenly Foxes and Dragon Stars\""s,
    "Kodoku \"Cannibalistic Insect\""s,
    "Kodoku \"Cave Swarmer\""s,
    "Kodoku \"Sky Pendra\""s,
    "Mining \"Ever-Accumulating Mine Dump\""s,
    "Mining \"Mine Blast\""s,
    "Mining \"Shield Method of the Youkai\""s,
    "Oomukade \"Snake Eater\""s,
    "Oomukade \"Dragon Eater\""s,
    "\"Kodoku Gourmet\""s,
    "\"Mushihime-sama's Resplendent and Restless Daily Life\""s,
};

// Touhou 18 Music
export const vector<string> th18_musicNames = {
    "unused"s,
    "A Rainbow Spanning Gensokyo"s,
    "unused"s,
    "A Shower of Strange Occurrences"s,
    "Kitten of Great Fortune"s,
    "The Cliff Hidden in Deep Green"s,
    "Banditry Technology"s,
    "The Perpetual Snow of Komakusa Blossoms"s,
    "Smoking Dragon"s,
    "The Obsolescent Industrial Remains"s,
    "Ore from the Age of the Gods"s,
    "The Long-Awaited Oumagatoki"s,
    "Starry Mountain of Tenma"s,
    "Lunar Rainbow"s,
    "Where Is That Bustling Marketplace Now ~ Immemorial Marketeers"s,
    "The Sunday After the Storm"s,
    "A Rainbow-Colored World"s,
    "The Great Fantastic Underground Railway Network"s,
    "The Princess Who Slays Dragon Kings"s,
};
