#include <string>
#pragma once

// Touhou 06
const std::string th06_musicNames[17] = {
	"A Dream More Scarlet than Red",
	"A Soul as Scarlet as a Ground Cherry",
	"Apparitions Stalk the Night",
	"Lunate Elf",
	"Tomboyish Girl in Love",
	"Shanghai Scarlet Teahouse ~ Chinese Tea",
	"Shanghai Alice of Meiji 17",
	"Voile, the Magic Library",
	"Locked Girl ~ The Girl's Sealed Room",
	"The Maid and the Pocket Watch of Blood",
	"Lunar Clock ~ Luna Dial",
	"The Young Descendant of Tepes",
	"Septette for a Dead Princess",
	"The Centennial Festival for Magical Girls",
	"U.N. Owen was Her?",
	"An Eternity More Transient than Scarlet",
	"Scarlet Tower ~ Eastern Dream...",
};

// Touhou 07
const std::string th07_musicNames[20] = {
	"Ghostly Dream ~ Snow or Cherry Petal",
	"Paradise ~ Deep Mountain",
	"Crystallized Silver",
	"The Fantastic Tales from Tono",
	"Diao Ye Zong (withered leaf)",
	"The Doll Maker of Bucuresti",
	"Doll Judgement ~ The Girl Who Played with People's Shapes",
	"The Capital City of Flowers in the Sky",
	"Phantom Band ~ Phantom Ensemble",
	"Eastern Ghostly Dream ~ Ancient Temple",
	"Hiroari Shoots a Strange Bird ~ Till When?",
	"Ultimate Truth",
	"Bloom Nobly, Ink-Black Cherry Blossom ~ Border of Life",
	"Border of Life",
	"Spiritual Domination",
	"A Maiden's Illusionary Funeral ~ Necro-Fantasy",
	"Spiritual Domination ~ Who done it!",
	"Necrofantasia",
	"Dream of a Spring Breeze",
	"Sakura, Sakura ~ Japanize Dream...",
};

// Touhou 08
const std::string th08_musicNames[21] = {
	"Eternal Night Vignette ~ Eastern Night",
	"Illusionary Night ~ Ghostly Eyes",
	"Stirring an Autumn Moon ~ Mooned Insect",
	"Song of the Night Sparrow ~ Night Bird",
	"Deaf to All but the Song",
	"Nostalgic Blood of the East ~ Old World",
	"Plain Asia",
	"Retribution for the Eternal Night ~ Imperishable Night",
	"Maiden's Capriccio ~ Dream Battle",
	"Love-Colored Master Spark",
	"Cinderella Cage ~ Kagome-Kagome",
	"Lunatic Eyes ~ Invisible Full Moon",
	"Voyage 1969",
	"Gensokyo Millennium ~ History of the Moon",
	"Flight of the Bamboo Cutter ~ Lunatic Princess",
	"Voyage 1970",
	"Extend Ash ~ Person of Hourai",
	"Reach for the Moon, Immortal Smoke",
	"Evening Primrose",
	"Eternal Dream ~ Mystical Maple",
	"Eastern Youkai Beauty",
};

// Touhou 09
const std::string th09_musicNames[19] = {
	"Flower Reflecting Mound ~ Higan Retour",
	"Spring Lane ~ Colorful Path",
	"Oriental Dark Flight",
	"Flowering Night",
	"Eastern Ghostly Dream ~ Ancient Temple",
	"Lunatic Eyes ~ Invisible Full Moon",
	"Adventure of the Lovestruck Tomboy",
	"Phantom Band ~ Phantom Ensemble",
	"Deaf to All but the Song ~ Flower Mix",
	"White Flag of Usa Shrine",
	"Wind God Girl",
	"Poison Body ~ Forsaken Doll",
	"Gensokyo, Past and Present ~ Flower Land",
	"Higan Retour ~ Riverside View",
	"Eastern Judgement in the Sixtieth Year ~ Fate of Sixty Years",
	"The Mound where the Flowers Reflect",
	"Mound of Shigan",
	"The Flowers Remain in Fantasy",
	"Flower of Soul ~ Another Dream...",
};

const std::string th09_stageNames[14] = {
	"Bamboo Forest of the Lost",
	"Bamboo Forest of the Lost",
	"Phantom Meadow",
	"Hakugyokurou's Stairway",
	"Eientei",
	"Misty Lake",
	"Barrier of Life & Death",
	"Youkai Trail",
	"Bamboo Forest of the Lost",
	"Garden of the Sun",
	"Giant Toad's Pond",
	"The Nameless Hill",
	"Road of Reconsideration",
	"Muenzuka",
};

const std::string th09_characterNames[16] = {
	"Reimu",
	"Marisa",
	"Sakuya",
	"Youmu",
	"Reisen",
	"Cirno",
	"Lyrica",
	"Mystia",
	"Tewi",
	"Yuuka",
	"Aya",
	"Medicine",
	"Komachi",
	"Eiki",
	"Merlin",
	"Lunasa",
};

// Touhou 08
const std::string th08_spellCardName[222] = {
	// stage 1 (13 cards)
	"Firefly Sign \"Meteors on Earth\"",
	"Firefly Sign \"Comets on Earth\"",
	"Lamp Sign \"Firefly Phenomenon\"",
	"Lamp Sign \"Firefly Phenomenon\"",
	"Lamp Sign \"Firefly Phenomenon\"",
	"Lamp Sign \"Firefly Phenomenon\"",
	"Wriggle Sign \"Little Bug\"",
	"Wriggle Sign \"Little Bug Storm\"",
	"Wriggle Sign \"Night Bug Storm\"",
	"Wriggle Sign \"Night Bug Tornado\"",
	"Hidden Bug \"Endless Night Seclusion\"",
	"Hidden Bug \"Endless Night Seclusion\"",
	"Hidden Bug \"Endless Night Seclusion\"",
	// stage 2 (19 cards)
	"Vocal Sign \"Hooting in the Night\"",
	"Vocal Sign \"Hooting in the Night\"",
	"Vocal Sign \"Howl of the Horned Owl\"",
	"Vocal Sign \"Howl of the Horned Owl\"",
	"Moth Sign \"Hawk Moth's Insect Curse\"",
	"Moth Sign \"Hawk Moth's Insect Curse\"",
	"Toxin Sign \"Poisonous Moth's Scales\"",
	"Deadly Toxin \"Poisonous Moth's Dance in the Dark\"",
	"Hawk Sign \"Ill - Starred Dive\"",
	"Hawk Sign \"Ill - Starred Dive\"",
	"Hawk Sign \"Ill - Starred Dive\"",
	"Hawk Sign \"Ill - Starred Dive\"",
	"Night-Blindness \"Song of the Night Sparrow\"",
	"Night-Blindness \"Song of the Night Sparrow\"",
	"Night-Blindness \"Song of the Night Sparrow\"",
	"Night-Blindness \"Song of the Night Sparrow\"",
	"Night Sparrow \"Midnight Chorus Master\"",
	"Night Sparrow \"Midnight Chorus Master\"",
	"Night Sparrow \"Midnight Chorus Master\"",
	// stage 3 (22 cards)
	"Spiritual Birth \"First Pyramid\"",
	"Spiritual Birth \"First Pyramid\"",
	"Spiritual Birth \"First Pyramid\"",
	"Spiritual Birth \"First Pyramid\"",
	"Origin Sign \"Ephemerality 137\"",
	"Origin Sign \"Ephemerality 137\"",
	"Origin Sign \"Ephemerality 137\"",
	"Ambition Sign \"Buretsu Crisis\"",
	"Ambition Sign \"Masakado Crisis\"",
	"Ambition Sign \"Yoshimitsu Crisis\"",
	"Ambition Sign \"General Headquarters Crisis\"",
	"Land Sign \"Three Sacred Treasures - Sword\"",
	"Land Sign \"Three Sacred Treasures - Orb\"",
	"Land Sign \"Three Sacred Treasures - Mirror\"",
	"Land Scheme \"Three Sacred Treasures - Country\"",
	"Ending Sign \"Phantasmal Emperor\"",
	"Ending Sign \"Phantasmal Emperor\"",
	"Pseudo-History \"The Legend of Gensokyo\"",
	"Pseudo-History \"The Legend of Gensokyo\"",
	"Future \"Gods' Realm\"",
	"Future \"Gods' Realm\"",
	"Future \"Gods' Realm\"",
	// stage 4A (23 cards)
	"Dream Sign \"Duplex Barrier\"",
	"Dream Sign \"Duplex Barrier\"",
	"Dream Sign \"Great Duplex Barrier\"",
	"Dream Sign \"Great Duplex Barrier\"",
	"Spirit Sign \"Fantasy Seal -Spread-\"",
	"Spirit Sign \"Fantasy Seal -Spread-\"",
	"Scattered Spirit \"Fantasy Seal -Worn-\"",
	"Scattered Spirit \"Fantasy Seal -Worn-\"",
	"Dream Sign \"Evil - Sealing Circle\"",
	"Dream Sign \"Evil - Sealing Circle\"",
	"Divine Arts \"Omnidirectional Oni - Binding Circle\"",
	"Divine Arts \"Omnidirectional Oni - Binding Circle\"",
	"Spirit Sign \"Fantasy Seal -Concentrate-\"",
	"Spirit Sign \"Fantasy Seal -Concentrate-\"",
	"Migrating Spirit \"Fantasy Seal -Marred-\"",
	"Migrating Spirit \"Fantasy Seal -Marred-\"",
	"Boundary \"Duplex Danmaku Barrier\"",
	"Boundary \"Duplex Danmaku Barrier\"",
	"Great Barrier \"Hakurei Danmaku Barrier\"",
	"Great Barrier \"Hakurei Danmaku Barrier\"",
	"Divine Spirit \"Fantasy Seal -Blink-\"",
	"Divine Spirit \"Fantasy Seal -Blink-\"",
	"Divine Spirit \"Fantasy Seal -Blink-\"",
	// stage 4B (23 cards)
	"Magic Sign \"Milky Way\"",
	"Magic Sign \"Milky Way\"",
	"Magic Space \"Asteroid Belt\"",
	"Magic Space \"Asteroid Belt\"",
	"Magic Sign \"Stardust Reverie\"",
	"Magic Sign \"Stardust Reverie\"",
	"Black Magic \"Event Horizon\"",
	"Black Magic \"Event Horizon\"",
	"Love Sign \"Non - Directional Laser\"",
	"Love Sign \"Non - Directional Laser\"",
	"Love Storm \"Starlight Typhoon\"",
	"Love Storm \"Starlight Typhoon\"",
	"Love Sign \"Master Spark\"",
	"Love Sign \"Master Spark\"",
	"Loving Heart \"Double Spark\"",
	"Loving Heart \"Double Spark\"",
	"Light Sign \"Earthlight Ray\"",
	"Light Sign \"Earthlight Ray\"",
	"Light Blast \"Shoot the Moon\"",
	"Light Blast \"Shoot the Moon\"",
	"Magicannon \"Final Spark\"",
	"Magicannon \"Final Spark\"",
	"Magicannon \"Final Master Spark\"",
	// stage 5 (19 cards)
	"Wave Sign \"Red-Eyed Hypnosis (Mind Shaker)\"",
	"Wave Sign \"Red-Eyed Hypnosis (Mind Shaker)\"",
	"Illusion Wave \"Red-Eyed Hypnosis (Mind Blowing)\"",
	"Illusion Wave \"Red-Eyed Hypnosis (Mind Blowing)\"",
	"Lunatic Sign \"Hallucinogenic Tuning (Visionary Tuning)\"",
	"Lunatic Sign \"Hallucinogenic Tuning (Visionary Tuning)\"",
	"Lunatic Gaze \"Lunatic Stare Tuning (Illusion Seeker)\"",
	"Lunatic Gaze \"Lunatic Stare Tuning (Illusion Seeker)\"",
	"Loafing Sign \"Life and Spirit Stopping (Idling Wave)\"",
	"Loafing Sign \"Life and Spirit Stopping (Idling Wave)\"",
	"Indolence \"Life and Spirit Stopping (Mind Stopper)\"",
	"Indolence \"Life and Spirit Stopping (Mind Stopper)\"",
	"Spread Sign \"Moon of Truth (Invisible Full Moon)\"",
	"Spread Sign \"Moon of Truth (Invisible Full Moon)\"",
	"Spread Sign \"Moon of Truth (Invisible Full Moon)\"",
	"Spread Sign \"Moon of Truth (Invisible Full Moon)\"",
	"Lunar Eyes \"Lunar Rabbit's Remote Mesmerism (Tele-Mesmerism)\"",
	"Lunar Eyes \"Lunar Rabbit's Remote Mesmerism (Tele-Mesmerism)\"",
	"Lunar Eyes \"Lunar Rabbit's Remote Mesmerism (Tele-Mesmerism)\"",
	// stage 6A (28 cards)
	"Spacesphere \"Earth in a Pot\"",
	"Spacesphere \"Earth in a Pot\"",
	"Spacesphere \"Earth in a Pot\"",
	"Spacesphere \"Earth in a Pot\"",
	"Awakened God \"Memories of the Age of the Gods\"",
	"Awakened God \"Memories of the Age of the Gods\"",
	"God Sign \"Genealogy of the Celestials\"",
	"God Sign \"Genealogy of the Celestials\"",
	"Revival \"Seimei Yugi -Life Game- \"",
	"Revival \"Seimei Yugi -Life Game- \"",
	"Resurrection \"Rising Game\"",
	"Resurrection \"Rising Game\"",
	"Leading God \"Omoikane's Device\"",
	"Leading God \"Omoikane's Device\"",
	"Mind of God \"Omoikane's Brain\"",
	"Mind of God \"Omoikane's Brain\"",
	"Curse of the Heavens \"Apollo 13\"",
	"Curse of the Heavens \"Apollo 13\"",
	"Curse of the Heavens \"Apollo 13\"",
	"Curse of the Heavens \"Apollo 13\"",
	"Esoterica \"Astronomical Entombing\"",
	"Esoterica \"Astronomical Entombing\"",
	"Esoterica \"Astronomical Entombing\"",
	"Esoterica \"Astronomical Entombing\"",
	"Forbidden Elixir \"Hourai Elixir\"",
	"Forbidden Elixir \"Hourai Elixir\"",
	"Forbidden Elixir \"Hourai Elixir\"",
	"Forbidden Elixir \"Hourai Elixir\"",
	// stage 6B (44 cards)
	"Medicine Sign \"Galaxy in a Pot\"",
	"Medicine Sign \"Galaxy in a Pot\"",
	"Medicine Sign \"Galaxy in a Pot\"",
	"Medicine Sign \"Galaxy in a Pot\"",
	"Impossible Request \"Jewel from the Dragon's Neck -Five-Colored Shots-\"",
	"Impossible Request \"Jewel from the Dragon's Neck -Five-Colored Shots-\"",
	"Divine Treasure \"Divine Dragon Bullet\"",
	"Divine Treasure \"Divine Dragon Bullet\"",
	"Impossible Request \"Buddha's Stone Bowl -Indomitable Will-\"",
	"Impossible Request \"Buddha's Stone Bowl -Indomitable Will-\"",
	"Divine Treasure \"Buddhist Diamond\"",
	"Divine Treasure \"Buddhist Diamond\"",
	"Impossible Request \"Robe of Fire Rat -Unhurried Mind-\"",
	"Impossible Request \"Robe of Fire Rat -Unhurried Mind-\"",
	"Divine Treasure \"Salamander Shield\"",
	"Divine Treasure \"Salamander Shield\"",
	"Impossible Request \"Swallow's Cowrie Shell -Everlasting Life-\"",
	"Impossible Request \"Swallow's Cowrie Shell -Everlasting Life-\"",
	"Divine Treasure \"Life Spring Infinity\"",
	"Divine Treasure \"Life Spring Infinity\"",
	"Impossible Request \"Bullet Branch of Hourai -Rainbow Danmaku -\"",
	"Impossible Request \"Bullet Branch of Hourai -Rainbow Danmaku -\"",
	"Divine Treasure \"Jeweled Branch of Hourai -Dreamlike Paradise-\"",
	"Divine Treasure \"Jeweled Branch of Hourai -Dreamlike Paradise-\"",
	"\"End of Imperishable Night -New Moon-\"",
	"\"End of Imperishable Night -Crescent Moon-\"",
	"\"End of Imperishable Night -First Quarter's Moon-\"",
	"\"End of Imperishable Night -Matsuyoi-\"",
	"\"End of Imperishable Night -11 o'Clock-\"",
	"\"End of Imperishable Night -Half to Midnight-\"",
	"\"End of Imperishable Night -Midnight-\"",
	"\"End of Imperishable Night -Half Past Midnight-\"",
	"\"End of Imperishable Night -1 o'Clock-\"",
	"\"End of Imperishable Night -Half Past 1-\"",
	"\"End of Imperishable Night -Dead of Night-\"",
	"\"End of Imperishable Night -Half Past 2-\"",
	"\"End of Imperishable Night -3 o'Clock-\"",
	"\"End of Imperishable Night -Half Past 3-\"",
	"\"End of Imperishable Night -4 o'Clock-\"",
	"\"End of Imperishable Night -Half Past 4-\"",
	"\"End of Imperishable Night -Morning Mist-\"",
	"\"End of Imperishable Night -Dawn-\"",
	"\"End of Imperishable Night -Morning Star-\"",
	"\"End of Imperishable Night -Rising World-\"",
	// extra stage (14 cards)
	"Past \"Old History of an Untrodden Land -Old History-\"",
	"Reincarnation \"Ichijou Returning Bridge\"",
	"Future \"New History of Fantasy -Next History-\"",
	"Limiting Edict \"Curse of Tsuki-no-Iwakasa\"",
	"Undying \"Fire Bird -Feng Wing Ascension-\"",
	"Fujiwara \"Wounds of Metsuzai Temple\"",
	"Undying \"Xu Fu's Dimension\"",
	"Expiation \"Honest Man's Death\"",
	"Hollow Being \"Wu\"",
	"Inextinguishable \"Phoenix's Tail\"",
	"Hourai \"South Wind, Clear Sky -Fujiyama Volcano-\"",
	"\"Possessed by Phoenix\"",
	"\"Hourai Doll\"",
	"\"Imperishable Shooting\"",
	// last words (17 cards)
	"\"Unseasonal Butterfly Storm\"",
	"\"Blind Nightbird\"",
	"\"Emperor of the Land of the Rising Sun\"",
	"\"Stare of the Hazy Phantom Moon (Lunatic Red Eyes)\"",
	"\"Heaven Spider's Butterfly-Capturing Web\"",
	"\"Tree-Ocean of Hourai\"",
	"\"Phoenix Rebirth\"",
	"\"Ancient Duper\"",
	"\"Total Purification\"",
	"\"Fantasy Nature\"",
	"\"Blazing Star\"",
	"\"Deflation World\"",
	"\"Matsuyoi-Reflecting Satellite Slash\"",
	"\"The Phantom of the Grand Guignol\"",
	"\"Scarlet Destiny\"",
	"\"Saigyouji Parinirvana\"",
	"\"Profound Danmaku Barrier -Phantasm, Foam and Shadow-\""
};

// Touhou 10
const std::string th10_musicNames[18] = {
	"A God That Misses People ~ Romantic Fall",
	"Because Princess Inada Is Scolding Me",
	"Sealed Gods",
	"The Road of the Misfortune God ~ Dark Road",
	"Dark Side of Fate",
	"The Gensokyo the Gods Loved",
	"Akutagawa Ryuunosuke's \"Kappa\" ~ Candid Friend",
	"Fall of Fall ~ Autumnal Waterfall",
	"Youkai Mountain ~ Mysterious Mountain",
	"The Primal Scene of Japan the Girl Saw",
	"Faith Is for the Transient People",
	"Cemetery of Onbashira ~ Grave of Being",
	"The Venerable Ancient Battlefield ~ Suwa Foughten Field",
	"Shrine at the Foot of the Mountain",
	"The Gods Give Us Blessed Rain ~ Sylphid Dream",
	"Tomorrow Will Be Special, Yesterday Was Not",
	"Native Faith",
	"Player's Score",
};

// Touhou 11
const std::string th11_musicNames[20] = {
	"Awakening of the Earth Spirits",
	"The Dark Blowhole",
	"The Sealed Youkai ~ Lost Place",
	"The Bridge People No Longer Cross",
	"unused",
	"Green-Eyed Jealousy",
	"Walking the Streets of a Former Hell",
	"A Flower-Studded Saké Dish on Mt. Ooe",
	"Heartfelt Fancy",
	"unused",
	"Satori Maiden ~ 3rd eye",
	"unused",
	"Lullaby of Deserted Hell",
	"Corpse Voyage ~ Be of good cheer!",
	"Hellfire Mantle",
	"Last Remote",
	"Solar Sect of Mystic Wisdom ~ Nuclear Fusion",
	"Hartmann's Youkai Girl",
	"The Earth Spirits' Homecoming",
	"Energy Daybreak ~ Future Dream...",
};

// Touhou 12
const std::string th12_musicNames[22] = {
	"At the End of Spring",
	"A Shadow in the Blue Sky",
	"A Tiny, Tiny, Clever Commander",
	"unused",
	"The Sealed Cloud Route",
	"Beware the Umbrella Left There Forever",
	"unused",
	"Sky Ruin",
	"The Traditional Old Man and the Stylish Girl",
	"Interdimensional Voyage of a Ghostly Passenger Ship",
	"Captain Murasa",
	"unused",
	"unused",
	"Rural Makai City Esoteria",
	"The Tiger-Patterned Bishamonten",
	"unused",
	"Fires of Hokkai",
	"Emotional Skyscraper ~ Cosmic Mind",
	"UFO Romance in the Night Sky",
	"Heian Alien",
	"Youkai Temple",
	"Returning Home from the Sky ~ Sky Dream",
};

// Touhou 12.8
const std::string th12_8_musicNames[12] = {
	"The Refrain of the Lovely Great War",
	"Year-Round Absorbed Curiosity",
	"Staking Your Life on a Prank",
	"unused",
	"unused",
	"A Midnight Fairy Dance",
	"Great Fairy Wars ~ Fairy Wars",
	"An Ice Fairy in Spring",
	"Player's Score",
	"An Ice Fairy in Spring - still -",
	"Loose Rain",
	"Magus Night",
};

// Touhou 13
const std::string th13_spellCardName[127] = {
	// stage 1 (14 cards)
	"Symbol \"Dance of the Dead Butterflies\"",
	"Symbol \"Dance of the Dead Butterflies\"",
	"Symbol \"Dance of the Dead Butterflies - Cherry Blossoms -\"",
	"Symbol \"Dance of the Dead Butterflies - Cherry Blossoms -\"",
	"Ghostly Butterfly \"Ghost Spot\"",
	"Ghostly Butterfly \"Ghost Spot\"",
	"Ghostly Butterfly \"Ghost Spot - Cherry Blossoms -\"",
	"Ghostly Butterfly \"Ghost Spot - Cherry Blossoms -\"",
	"Nether Sign \"Endless Evening Cherry Blossoms\"",
	"Nether Sign \"Endless Evening Cherry Blossoms\"",
	"Nether Sign \"Endless Evening Cherry Blossoms\"",
	"Nether Sign \"Endless Evening Cherry Blossoms\"",
	"Cherry Blossom Sign \"Saigyou Cherry Blossom Blizzard\"",
	"Cherry Blossom Sign \"Saigyou Cherry Blossom Blizzard\"",
	// stage 2 (16 cards)
	"Echo Sign \"Mountain Echo\"",
	"Echo Sign \"Mountain Echo\"",
	"Echo Sign \"Mountain Echo Scramble\"",
	"Echo Sign \"Mountain Echo Scramble\"",
	"Echo Sign \"Power Resonance\"",
	"Echo Sign \"Power Resonance\"",
	"Echo Sign \"Power Resonance\"",
	"Echo Sign \"Power Resonance\"",
	"Mountain Echo \"Long-Range Echo\"",
	"Mountain Echo \"Long-Range Echo\"",
	"Mountain Echo \"Amplify Echo\"",
	"Mountain Echo \"Amplify Echo\"",
	"Great Voice \"Charged Cry\"",
	"Great Voice \"Charged Cry\"",
	"Great Voice \"Charged Yahoo!\"",
	"Great Voice \"Charged Yahoo!\"",
	// stage 3 (14 cards)
	"Rainbow Sign \"Umbrella Cyclone\"",
	"Rainbow Sign \"Umbrella Cyclone\"",
	"Recovery \"Heal By Desire\"",
	"Recovery \"Heal By Desire\"",
	"Recovery \"Heal By Desire\"",
	"Recovery \"Heal By Desire\"",
	"Poison Nail \"Poison Raze\"",
	"Poison Nail \"Poison Raze\"",
	"Poison Nail \"Poison Murder\"",
	"Poison Nail \"Poison Murder\"",
	"Desire Sign \"Score Desire Spirit Invitation\"",
	"Desire Sign \"Score Desire Spirit Invitation\"",
	"Desire Sign \"Score Desire Eater\"",
	"Desire Sign \"Score Desire Eater\"",
	// stage 4 (15 cards)
	"Evil Sign \"Yang Xiaogui\"",
	"Evil Sign \"Guhun Yegui\"",
	"Evil Sign \"Guhun Yegui\"",
	"Demonify \"Zouhuo Rumo\"",
	"Demonify \"Zouhuo Rumo\"",
	"Demonify \"Zouhuo Rumo\"",
	"Demonify \"Zouhuo Rumo\"",
	"Possession \"Corpse Tongji\"",
	"Possession \"Corpse Tongji\"",
	"Spirit Link \"Tongling Yoshika\"",
	"Spirit Link \"Tongling Yoshika\"",
	"Path Sign \"Tao Fetal Movement\"",
	"Path Sign \"Tao Fetal Movement\"",
	"Path Sign \"Tao Fetal Movement\"",
	"Path Sign \"Tao Fetal Movement\"",
	// stage 5 (19 cards)
	"Thunder Arrow \"Gagouji's Cyclone\"",
	"Thunder Arrow \"Gagouji's Cyclone\"",
	"Thunder Arrow \"Gagouji's Tornado\"",
	"Heaven Sign \"Rainy Iwafune\"",
	"Heaven Sign \"Rainy Iwafune\"",
	"Heaven Sign \"Iwafune Ascending to Heaven\"",
	"Heaven Sign \"Iwafune Ascending to Heaven\"",
	"Throwing Dishes \"Mononobe's Eighty Sake Cups\"",
	"Throwing Dishes \"Mononobe's Eighty Sake Cups\"",
	"Throwing Dishes \"Mononobe's Eighty Sake Cups\"",
	"Throwing Dishes \"Mononobe's Eighty Sake Cups\"",
	"Blaze Sign \"Blazing Winds of Haibutsu\"",
	"Blaze Sign \"Blazing Winds of Haibutsu\"",
	"Blaze Sign \"Sakuraiji in Flames\"",
	"Blaze Sign \"Sakuraiji in Flames\"",
	"Saint Girl \"Oomonoimi's Dinner\"",
	"Saint Girl \"Oomonoimi's Dinner\"",
	"Saint Girl \"Oomonoimi's Dinner\"",
	"Saint Girl \"Oomonoimi's Dinner\"",
	// stage 6 (28 cards)
	"Honor \"Colors of Twelve Levels\"",
	"Honor \"Colors of Twelve Levels\"",
	"Honor \"Ranks of Twelve Levels\"",
	"Honor \"Ranks of Twelve Levels\"",
	"Hermit Sign \"Taoist of the Land of the Rising Sun\"",
	"Hermit Sign \"Taoist of the Land of the Rising Sun\"",
	"Hermit Sign \"Emperor of the Land of the Rising Sun\"",
	"Hermit Sign \"Emperor of the Land of the Rising Sun\"",
	"Summon \"Royal Clan's Chaotic Dance\"",
	"Summon \"Royal Clan's Chaotic Dance\"",
	"Summon \"Royal Clan's Chaotic Dance\"",
	"Summon \"Royal Clan's Chaotic Dance\"",
	"Secret Treasure \"Armillary Sphere of Ikaruga-dera\"",
	"Secret Treasure \"Armillary Sphere of Ikaruga-dera\"",
	"Secret Treasure \"Armillary Sphere of Ikaruga-dera\"",
	"Secret Treasure \"Prince Shotoku's Out-of-Place Artifact\"",
	"Light Sign \"Halo of the Guse Kannon\"",
	"Light Sign \"Halo of the Guse Kannon\"",
	"Light Sign \"Guse Flash\"",
	"Light Sign \"Guse Flash\"",
	"Discernment \"Laser of Seventeen Articles\"",
	"Discernment \"Laser of Seventeen Articles\"",
	"Divine Light \"Honour the Avoidance of Defiance\"",
	"Divine Light \"Honour the Avoidance of Defiance\"",
	"\"Falling Stars on Divine Spirit Mausoleum\"",
	"\"Falling Stars on Divine Spirit Mausoleum\"",
	"\"Newborn Divine Spirit\"",
	"\"Newborn Divine Spirit\"",
	// extra stage (13 cards)
	"Unknown \"Will-o'-wisps in Unknown Orbit\"",
	"Unknown \"Skyfish with Unknown Shape\"",
	"Unknown \"Youkai Orb of Unknown Mechanics\"",
	"First Duel \"Primate Danmaku Transformation\"",
	"Second Duel \"Carnivorous Danmaku Transformation\"",
	"Third Duel \"Avian Danmaku Transformation\"",
	"Fourth Duel \"Amphibian Danmaku Transformation\"",
	"Fifth Duel \"Scrolls of Frolicking Animals\"",
	"Sixth Duel \"Tanuki's Monstrous School\"",
	"Seventh Duel \"Wild Deserted Island\"",
	"Transformation \"Pseudo-Exorcism of the Stupid Shrine Maiden\"",
	"\"Mamizou Danmaku in Ten Transformations\"",
	"Mujina Sign \"Full Moon Pompokolin\"",
	// OVERDRIVE (8 cards)
	"Cherry Blossom Sign \"Cherry Blossom Blizzard Hell\"",
	"Mountain Echo \"Yamabiko's Specialty Echo Demonstration\"",
	"Poison Nail \"Undead Murderer\"",
	"Path Sign \"TAO Fetal Movement ~Dao~\"",
	"Vengeful Spirit \"Iruka's Thunder\"",
	"Saint Girl \"Sun Goddess's Sacrifice\"",
	"\"Divine Spirits' Macrocosm\"",
	"\"Wild Carpet\""
};

// Touhou 13 Music
const std::string th13_musicNames[22] = {
	"Spirit of Avarice",
	"Night Sakura of Dead Spirits",
	"unused",
	"Ghost Lead",
	"Welcome to Youkai Temple",
	"unused",
	"Youkai Girl at the Gate",
	"Let's Live in a Lovely Cemetery",
	"Rigid Paradise",
	"unused",
	"Desire Drive",
	"Old Yuanxian",
	"The Hall of Dreams' Great Mausoleum",
	"unused",
	"unused",
	"Omiwa Legend",
	"Starry Sky of Small Desires",
	"Shoutoku Legend ~ True Administrator",
	"A New Wind at the Shrine",
	"Desire Dream",
	"Youkai Back Shrine Road",
	"Futatsuiwa from Sado",
};

// Touhou 14 Spell Cards
const std::string th14_spellCardName[120] = {
	// stage 1 (1-10) (10 cards)
	"Ice Sign \"Ultimate Blizzard\"",
	"Ice Sign \"Ultimate Blizzard\"",
	"Water Sign \"Tail Fin Slap\"",
	"Water Sign \"Tail Fin Slap\"",
	"Water Sign \"Tail Fin Slap\"",
	"Water Sign \"Tail Fin Slap\"",
	"Scale Sign \"Scale Wave\"",
	"Scale Sign \"Scale Wave\"",
	"Scale Sign \"Raging Waves of the Reversed Scale\"",
	"Scale Sign \"Great Raging Waves of the Reversed Scale\"",
	// stage 2 (11-26) (16 cards)
	"Flight Sign \"Flying Head\"",
	"Flight Sign \"Flying Head\"",
	"Flight Sign \"Flying Head\"",
	"Flight Sign \"Flying Head\"",
	"Neck Sign \"Close - Eye Shot\"",
	"Neck Sign \"Close - Eye Shot\"",
	"Neck Sign \"Rokurokubi Flight\"",
	"Neck Sign \"Rokurokubi Flight\"",
	"Flying Head \"Multiplicative Head\"",
	"Flying Head \"Multiplicative Head\"",
	"Flying Head \"Seventh Head\"",
	"Flying Head \"Ninth Head\"",
	"Flying Head \"Dullahan Night\"",
	"Flying Head \"Dullahan Night\"",
	"Flying Head \"Dullahan Night\"",
	"Flying Head \"Dullahan Night\"",
	// stage 3 (27-40) (14 cards)
	"Fang Sign \"Moonlit Canine Teeth\"",
	"Fang Sign \"Moonlit Canine Teeth\"",
	"Transformation \"Triangle Fang\"",
	"Transformation \"Triangle Fang\"",
	"Transformation \"Star Fang\"",
	"Transformation \"Star Fang\"",
	"Roar \"Strange Roar\"",
	"Roar \"Strange Roar\"",
	"Roar \"Full Moon Howling\"",
	"Roar \"Full Moon Howling\"",
	"Wolf Sign \"Star Ring Pounce\"",
	"Wolf Sign \"Star Ring Pounce\"",
	"Sirius \"High-Speed Pounce\"",
	"Sirius \"High-Speed Pounce\"",
	// stage 4 (41-64) (24 cards)
	"Heikyoku \"Sounds of Jetavana's Bell\"",
	"Heikyoku \"Sounds of Jetavana's Bell\"",
	"Heikyoku \"Sounds of Jetavana's Bell\"",
	"Heikyoku \"Sounds of Jetavana's Bell\"",
	"Vengeful Spirit \"Hoichi the Earless\"",
	"Vengeful Spirit \"Hoichi the Earless\"",
	"Vengeful Spirit \"Great Vengeful Spirit of Taira\"",
	"Vengeful Spirit \"Great Vengeful Spirit of Taira\"",
	"Music Sign \"Wicked Musical Score\"",
	"Music Sign \"Wicked Musical Score\"",
	"Music Sign \"Malicious Musical Score\"",
	"Music Sign \"Double Score\"",
	"Koto Sign \"Sounds of Anicca's Koto\"",
	"Koto Sign \"Sounds of Anicca's Koto\"",
	"Koto Sign \"Sounds of Anicca's Koto\"",
	"Koto Sign \"Sounds of Anicca's Koto\"",
	"Echo Sign \"Heian's Reverberation\"",
	"Echo Sign \"Heian's Reverberation\"",
	"Echo Sign \"Echo Chamber\"",
	"Echo Sign \"Echo Chamber\"",
	"Koto Music \"Social Upheaval Koto Dirge\"",
	"Koto Music \"Social Upheaval Koto Dirge\"",
	"Koto Music \"Social Upheaval Requiem\"",
	"Koto Music \"Social Upheaval Requiem\"",
	// stage 5 (65-84) (20 cards)
	"Deceit Sign \"Reverse Needle Attack\"",
	"Deceit Sign \"Reverse Needle Attack\"",
	"Deceit Sign \"Reverse Needle Attack\"",
	"Deceit Sign \"Reverse Needle Attack\"",
	"Reverse Sign \"Danmaku Through the Looking-Glass\"",
	"Reverse Sign \"Danmaku Through the Looking-Glass\"",
	"Reverse Sign \"Evil in the Mirror\"",
	"Reverse Sign \"Evil in the Mirror\"",
	"Reverse Sign \"This Side Down\"",
	"Reverse Sign \"This Side Down\"",
	"Reverse Sign \"Overturning All Under Heaven\"",
	"Reverse Sign \"Overturning All Under Heaven\"",
	"Reverse Bow \"Dream Bow of Heaven & Earth\"",
	"Reverse Bow \"Dream Bow of Heaven & Earth\"",
	"Reverse Bow \"Decree of the Dream Bow of Heaven & Earth\"",
	"Reverse Bow \"Decree of the Dream Bow of Heaven & Earth\"",
	"Turnabout \"Reverse Hierarchy\"",
	"Turnabout \"Reverse Hierarchy\"",
	"Turnabout \"Change Air Brave\"",
	"Turnabout \"Change Air Brave\"",
	// stage 6 (85-108) (24 cards)
	"Small Bullet \"Inchling's Path\"",
	"Small Bullet \"Inchling's Path\"",
	"Small Bullet \"Inchling's Thorny Path\"",
	"Small Bullet \"Inchling's Thorny Path\"",
	"Mallet \"Grow Bigger!\"",
	"Mallet \"Grow Bigger!\"",
	"Mallet \"Grow Even Bigger!\"",
	"Mallet \"Grow Even Bigger!\"",	"Bewitched Sword \"Shining Needle Sword\"",
	"Bewitched Sword \"Shining Needle Sword\"",
	"Bewitched Sword \"Shining Needle Sword\"",
	"Bewitched Sword \"Shining Needle Sword\"",
	"Mallet \"You Grow Bigger!\"",
	"Mallet \"You Grow Bigger!\"",
	"Mallet \"You Grow Bigger!\"",
	"Mallet \"You Grow Bigger!\"",
	"\"Attack on Dwarf\"",
	"\"Attack on Dwarf\"",
	"\"Wall of Issun\"",
	"\"Wall of Issun\"",
	"\"Hop-o'-My-Thumb Seven\"",
	"\"Hop-o'-My-Thumb Seven\"",
	"\"The Seven Issun-Boushi\"",
	"\"The Seven Issun-Boushi\"",
	// extra stage (109-120) (12 cards)
	"String Music \"Storm Ensemble\"",
	"String Music \"Joururi World\"",
	"First Drum \"Raging Temple Taiko\"",
	"Second Drum \"Vengeful Spirit Aya-no-Tsuzumi\"",
	"Third Drum \"Three Strikes at Midnight\"",
	"Death Drum \"Land Percuss\"",
	"Fifth Drum \"Den-Den Daiko\"",
	"Sixth Drum \"Alternate Sticking\"",
	"Seventh Drum \"High Speed Taiko Rocket\"",
	"Eighth Drum \"Thunder God's Anger\"",
	"\"Blue Lady Show\"",
	"\"Pristine Beat\"",
};

// Touhou 14 Music
const std::string th14_musicNames[20] = {
	"unused",
	"Mysterious Purification Rod",
	"Mist Lake",
	"Mermaid from the Uncharted Land",
	"Humans and Youkai Traversing the Canal",
	"Dullahan Under the Willows",
	"Bamboo Forest of the Full Moon",
	"Lonesome Werewolf",
	"unused",
	"Magical Storm",
	"Illusionary Joururi",
	"The Shining Needle Castle Sinking in the Air",
	"Reverse Ideology",
	"unused",
	"The Exaggerated Castle Keep",
	"Inchlings of the Shining Needle ~ Little Princess",
	"Magical Power of the Mallet",
	"Mysterious, Mysterious Tools",
	"Thunderclouds of Magical Power",
	"Primordial Beat ~ Pristine Beat",
};

// Touhou 15 Music
const std::string th15_musicNames[18] = {
	"unused",
	"The Space Shrine Maiden Appears",
	"Unforgettable, the Nostalgic Greenery",
	"The Lake Reflects the Cleansed Moonlight",
	"The Rabbit Has Landed",
	"September Pumpkin",
	"The Mysterious Shrine Maiden Flying Through Space",
	"Eternal Spring Dream",
	"The Frozen Eternal Capital",
	"Reversed Wheel of Fortune",
	"Faraway Voyage of 380,000 Kilometers",
	"Pierrot of the Star-Spangled Banner",
	"The Sea that Reflects One's Home Planet",
	"Pure Furies ~ Whereabouts of the Heart",
	"The Moon as Seen from the Shrine",
	"The Space Shrine Maiden Returns Home",
	"A World of Nightmares Never Seen Before",
	"Pandemonic Planet",
};

// Touhou 16
const std::string th16_spellCardName[119] = {
	// stage 1 (8 cards)
	"Butterfly Sign \"Minute Scales\"",
	"Butterfly Sign \"Minute Scales\"",
	"Butterfly Sign \"Swallowtail's Scales\"",
	"Butterfly Sign \"Swallowtail's Scales\"",
	"Butterfly Sign \"Fluttering Summer\"",
	"Butterfly Sign \"Fluttering Summer\"",
	"Butterfly Sign \"Midsummer Wingbeats\"",
	"Butterfly Sign \"Midsummer Wingbeats\"",
	// stage 2 (12 cards)
	"Rain Sign \"Imprisoning Autumn Rain\"",
	"Rain Sign \"Imprisoning Autumn Rain\"",
	"Rain Sign \"Cursed Torrential Rain\"",
	"Rain Sign \"Cursed Torrential Rain\"",
	"Blade Sign \"Yamanba's Kitchen Knife Sharpening\"",
	"Blade Sign \"Yamanba's Kitchen Knife Sharpening\"",
	"Blade Sign \"Yamanba's Oni Kitchen Knife Sharpening\"",
	"Blade Sign \"Yamanba's Oni Kitchen Knife Sharpening\"",
	"Blade Exhaustion Sign \"Mountain Murder\"",
	"Blade Exhaustion Sign \"Mountain Murder\"",
	"Blade Exhaustion Sign \"Bloody Mountain Murder\"",
	"Blade Exhaustion Sign \"Bloody Mountain Murder\"",
	// stage 3 (14 cards)
	"Spring Sign \"Surprise Spring\"",
	"Spring Sign \"Surprise Spring\"",
	"Dog Sign \"Stray Dog's Walk\"",
	"Dog Sign \"Stray Dog's Walk\"",
	"Hound Sign \"Mountain Hound's Walk\"",
	"Hound Sign \"Mountain Hound's Walk\"",
	"Spinning Top \"Koma-Inu Spin\"",
	"Spinning Top \"Koma-Inu Spin\"",
	"Spinning Top \"Koma-Inu Spin\"",
	"Spinning Top \"Curl Up And Die\"",
	"Koma Sign \"Solitary A-Un Breathing\"",
	"Koma Sign \"Solitary A-Un Breathing\"",
	"Koma Sign \"Solitary A-Un Breathing\"",
	"Koma Sign \"Solitary A-Un Breathing\"",
	// stage 4 (12 cards)
	"Magic Sign \"Instant Bodhi\"",
	"Magic Sign \"Instant Bodhi\"",
	"Magic Sign \"Bodhi in an Instant\"",
	"Magic Sign \"Bodhi in an Instant\"",
	"Magic Sign \"Bullet Golem\"",
	"Magic Sign \"Bullet Golem\"",
	"Magic Sign \"Gigantic Pet Bullet Lifeform\"",
	"Magic Sign \"Gigantic Pet Bullet Lifeform\"",
	"Jizo \"Criminal Salvation\"",
	"Jizo \"Criminal Salvation\"",
	"Jizo \"Hellfire Salvation\"",
	"Jizo \"Hellfire Salvation\"",
	// stage 5 (24 cards)
	"Bamboo Sign \"Bamboo Spear Dance\"",
	"Bamboo Sign \"Bamboo Spear Dance\"",
	"Bamboo Sign \"Bamboo Crazy Dance\"",
	"Bamboo Sign \"Bamboo Crazy Dance\"",
	"Myoga Ginger \"Forget Your Name\"",
	"Myoga Ginger \"Forget Your Name\"",
	"Myoga Ginger \"Forget Your Name\"",
	"Myoga Ginger \"Forget Your Name\"",
	"Broadleaf Sign \"Tanabata Star Festival\"",
	"Broadleaf Sign \"Tanabata Star Festival\"",
	"Broadleaf Sign \"Tanabata Star Festival\"",
	"Broadleaf Sign \"Tanabata Star Festival\"",
	"Myoga Blessing \"Behind You\"",
	"Myoga Blessing \"Behind You\"",
	"Myoga Blessing \"Behind You\"",
	"Myoga Blessing \"Behind You\"",
	"Dance Sign \"Behind Festival\"",
	"Dance Sign \"Behind Festival\"",
	"Dance Sign \"Behind Festival\"",
	"Dance Sign \"Behind Festival\"",
	"Mad Dance \"Tengu-Odoshi\"",
	"Mad Dance \"Tengu-Odoshi\"",
	"Mad Dance \"Frenzied Tengu-Frightening\"",
	"Mad Dance \"Frenzied Tengu-Frightening\"",
	// stage 6 (36 cards, 16 of which are season finals damn I hate it)
	"Back Sign \"Halo of the Secret God\"",
	"Back Sign \"Halo of the Secret God\"",
	"Back Sign \"Halo of the Secret God\"",
	"Back Sign \"Halo of the Absolute Secret God\"",
	"Hidden Summer \"Scorch by Hot Summer\"",
	"Hidden Summer \"Scorch by Hot Summer\"",
	"Hidden Summer \"Scorched Earth of Abnormal Intense Heat\"",
	"Hidden Summer \"Scorched Earth of Abnormal Intense Heat\"",
	"Hidden Fall \"Die of Famine\"",
	"Hidden Fall \"Die of Famine\"",
	"Hidden Fall \"Preta of Abnormal Blight\"",
	"Hidden Fall \"Preta of Abnormal Blight\"",
	"Hidden Winter \"Black Snowman\"",
	"Hidden Winter \"Black Snowman\"",
	"Hidden Winter \"Snowman of Abnormal Snowfall\"",
	"Hidden Winter \"Snowman of Abnormal Snowfall\"",
	"Hidden Spring \"April Wizard\"",
	"Hidden Spring \"April Wizard\"",
	"Hidden Spring \"Black Magician of Abnormal Falling Petals\"",
	"Hidden Spring \"Black Magician of Abnormal Falling Petals\"",
	"\"Hidden Breezy Cherry Blossom\"",
	"\"Hidden Breezy Cherry Blossom\"",
	"\"Hidden Breezy Cherry Blossom\"",
	"\"Hidden Breezy Cherry Blossom\"",
	"\"Hidden Perfect Summer Ice\"",
	"\"Hidden Perfect Summer Ice\"",
	"\"Hidden Perfect Summer Ice\"",
	"\"Hidden Perfect Summer Ice\"",
	"\"Hidden Crazy Fall Wind\"",
	"\"Hidden Crazy Fall Wind\"",
	"\"Hidden Crazy Fall Wind\"",
	"\"Hidden Crazy Fall Wind\"",
	"\"Hidden Extreme Winter\"",
	"\"Hidden Extreme Winter\"",
	"\"Hidden Extreme Winter\"",
	"\"Hidden Extreme Winter\"",
	// extra stage (13 cards)
	"Drum Dance \"Powerful Cheers\"",
	"Mad Dance \"Crazy Backup Dance\"",
	"Bullet Dance \"Two-Eyed Typhoon\"",
	"Secret Ceremony \"Reverse Invoker\"",
	"Secret Ceremony \"Rear Shots of Betrayal\"",
	"Secret Ceremony \"Danmaku Dupion\"",
	"Secret Ceremony \"Fire of Ena\"",
	"Secret Ceremony \"Kyogen of the Back Door\"",
	"Secret Ceremony \"Matarah Dukkha\"",
	"Secret Ceremony \"Sword of the Seven Stars\"",
	"Secret Ceremony \"Performers Unattached to Society\"",
	"\"The Back Face's Dark Sarugaku\"",
	"\"Anarchy Bullet Hell\""
};

// Touhou 16 Music
const std::string th16_musicNames[18] = {
	"unused",
	"The Sky Where Cherry Blossoms Flutter Down",
	"A Star of Hope Rises in the Blue Sky",
	"A Midsummer Fairy's Dream",
	"The Colorless Wind on Youkai Mountain",
	"Deep-Mountain Encounter",
	"Swim in a Cherry Blossom-Colored Sea",
	"A Pair of Divine Beasts",
	"Illusionary White Traveler",
	"The Magic Straw-Hat Jizo",
	"Does the Forbidden Door Lead to This World, or the World Beyond?",
	"Crazy Backup Dancers",
	"The Concealed Four Seasons",
	"Into Backdoor",
	"Unnatural Nature",
	"White Traveler",
	"No More Going Through Doors",
	"Secret God Matara ~ Hidden Star in All Seasons.",
};

// Touhou 17
const std::string th17_spellCardName[101] = {
	// stage 1 (1-8, 8 cards)
	"Stone Sign \"Stone Woods\"",
	"Stone Sign \"Stone Woods\"",
	"Stone Sign \"Stone Conifers\"",
	"Stone Sign \"Stone Conifers\"",
	"Stone Sign \"Children's Limbo\"",
	"Stone Sign \"Children's Limbo\"",
	"Stone Sign \"Adult Children's Limbo\"",
	"Stone Sign \"Adult Children's Limbo\"",
	// stage 2 (9-20, 12 cards)
	"Stone Sign \"Stone Baby\"",
	"Stone Sign \"Stone Baby\"",
	"Stone Sign \"Heavy Stone Baby\"",
	"Stone Sign \"Heavy Stone Baby\"",
	"Drowning Sign \"Drowning in the Sanzu\"",
	"Drowning Sign \"Drowning in the Sanzu\"",
	"Drowning Sign \"Drowning in the Sanzu\"",
	"Drowning Sign \"Drowning in the Sanzu\"",
	"Oni Sign \"Demon Siege\"",
	"Oni Sign \"Demon Siege\"",
	"Oni Sign \"Hungry Demon Siege\"",
	"Oni Sign \"Hungry Demon Siege\"",
	// stage 3 (21-32, 12 cards)
	"Water Sign \"Ordeal of Water Distribution\"",
	"Water Sign \"Ordeal of Water Distribution\"",
	"Water Sign \"High-Level Purgatordeal of Water Distribution\"",
	"Water Sign \"Ultimate Purgatordeal of Water Distribution\"",
	"Light Sign \"Ordeal of Surveying\"",
	"Light Sign \"Ordeal of Surveying\"",
	"Light Sign \"High-Level Purgatordeal of Surveying\"",
	"Light Sign \"Ultimate Purgatordeal of Surveying\"",
	"Oni Sign \"Purgatordeal of Oniwatari\"",
	"Oni Sign \"Purgatordeal of Oniwatari\"",
	"Oni Sign \"High-Level Purgatordeal of Oniwatari\"",
	"Oni Sign \"Hell-Level Purgatordeal of Oniwatari\"",
	// stage 4 (33-44, 12 cards)
	"Tortoise Sign \"Tortoiseshell Hell\"",
	"Tortoise Sign \"Tortoiseshell Hell\"",
	"Tortoise Sign \"Tortoiseshell Hell\"",
	"Tortoise Sign \"Tortoiseshell Hell\"",
	"Oni Sign \"Beasts Attacking from the Rear\"",
	"Oni Sign \"Beasts Attacking from the Rear\"",
	"Oni Sign \"Mangy Beasts Attacking from the Rear\"",
	"Oni Sign \"Devilish Beasts Attacking from the Rear\"",
	"Dragon Sign \"Dragon Crest Bullets\"",
	"Dragon Sign \"Dragon Crest Bullets\"",
	"Dragon Sign \"Dragon Crest Bullets\"",
	"Dragon Sign \"Dragon Crest Bullets\"",
	// stage 5 (45-60, 16 cards)
	"Haniwa \"Archer Haniwa\"",
	"Haniwa \"Archer Haniwa\"",
	"Haniwa \"Skilled Archer Haniwa\"",
	"Haniwa \"Skilled Archer Haniwa\"",
	"Haniwa \"Fencer Haniwa\"",
	"Haniwa \"Fencer Haniwa\"",
	"Haniwa \"Skilled Fencer Haniwa\"",
	"Haniwa \"Skilled Fencer Haniwa\"",
	"Haniwa \"Cavalry Haniwa\"",
	"Haniwa \"Cavalry Haniwa\"",
	"Haniwa \"Skilled Cavalry Haniwa\"",
	"Haniwa \"Skilled Cavalry Haniwa\"",
	"Haniwa \"Hollow Inexhaustible Troops\"",
	"Haniwa \"Hollow Inexhaustible Troops\"",
	"Haniwa \"Undefeated Inexhaustible Troops\"",
	"Haniwa \"Undefeated Inexhaustible Troops\"",
	// stage 6 (61-88, 18 cards)
	"Square Shape \"Square-Shaped Sculpting Art\"",
	"Square Shape \"Square-Shaped Sculpting Art\"",
	"Square Shape \"Square Creature\"",
	"Square Shape \"Square Creature\"",
	"Circular Shape \"Perfect Circle Sculpting Art\"",
	"Circular Shape \"Perfect Circle Sculpting Art\"",
	"Circular Shape \"Circle Creature\"",
	"Circular Shape \"Circle Creature\"",
	"Linear Shape \"Line-Shaped Sculpting Art\"",
	"Linear Shape \"Line-Shaped Sculpting Art\"",
	"Linear Shape \"Linear Creature\"",
	"Linear Shape \"Linear Creature\"",
	"Haniwa \"Horse-and-Rider Idol Sculpting Art\"",
	"Haniwa \"Horse-and-Rider Idol Sculpting Art\"",
	"Haniwa \"Idol Creature\"",
	"Haniwa \"Idol Creature\"",
	"\"Oni-Shaped Sculpting Art\"",
	"\"Oni-Shaped Sculpting Art\"",
	"\"Oni-Shaped Sculpting Art\"",
	"\"Oni-Shaped Sculpting Art\"",
	"\"Geometric Creature\"",
	"\"Geometric Creature\"",
	"\"Geometric Creature\"",
	"\"Geometric Creature\"",
	"\"Idola Diabolus\"",
	"\"Idola Diabolus\"",
	"\"Idola Diabolus\"",
	"\"Idola Diabolus\"",
	// extra stage (89-101, 13 cards)
	"Bloody Battle \"Watershed of Blood\"",
	"Bloody Battle \"Hell Realm Sight-Line\"",
	"Bloody Battle \"All-Spirit Oniwatari\"",
	"Agile Skill \"Thrilling Shot\"",
	"Agile Skill \"Lightning Neigh\"",
	"Agile Skill \"Dense Crowd\"",
	"Agile Skill \"Beast Epidemicity\"",
	"Agile Skill \"Triangle Chase\"",
	"Agile Skill \"Black Pegasus Meteor Shot\"",
	"Agile Skill \"Muscle Explosion\"",
	"\"Follow Me, Unafraid\"",
	"\"Oni-Shaped Hoi Polloi\"",
	"\"Deeds of Devilish Beasts\"",
};

// Touhou 17 Music
const std::string th17_musicNames[19] = {
	"unused",
	"Silent Beast Spirits",
	"unused",
	"The Lamentations Known Only to Jizo",
	"Jelly Stone",
	"Lost River",
	"The Stone Baby and the Submerged Bovine",
	"Everlasting Red Spider Lily",
	"Seraphic Chicken",
	"Unlocated Hell",
	"Tortoise Dragon ~ Fortune and Misfortune",
	"Beast Metropolis",
	"Joutoujin of Ceramics",
	"Entrust the World to Idols ~ Idolatrize World",
	"Electric Heritage",
	"The Animals' Rest",
	"Return from the Underground",
	"The Shining Law of the Strong Eating the Weak",
	"Prince Shoutoku's Pegasus ~ Dark Pegasus",
};