#include <string>
#pragma once

// Touhou 08
const std::string th08_spellCardName[222] = {
	// stage 1 (13 cards)
	"Firefly Sign \"Meteors on Earth\"",
	"Firefly Sign \"Comets on Earth\"",
	"Lamp Sign \"Firefly Phenomenon\"",
	"Lamp Sign \"Firefly Phenomenon\"",
	"Lamp Sign \"Firefly Phenomenon\"",
	"Lamp Sign \"Firefly Phenomenon\"",
	"Wriggle Sign \"Little Bug\"",
	"Wriggle Sign \"Little Bug Storm\"",
	"Wriggle Sign \"Night Bug Storm\"",
	"Wriggle Sign \"Night Bug Tornado\"",
	"Hidden Bug \"Endless Night Seclusion\"",
	"Hidden Bug \"Endless Night Seclusion\"",
	"Hidden Bug \"Endless Night Seclusion\"",
	// stage 2 (19 cards)
	"Vocal Sign \"Hooting in the Night\"",
	"Vocal Sign \"Hooting in the Night\"",
	"Vocal Sign \"Howl of the Horned Owl\"",
	"Vocal Sign \"Howl of the Horned Owl\"",
	"Moth Sign \"Hawk Moth's Insect Curse\"",
	"Moth Sign \"Hawk Moth's Insect Curse\"",
	"Toxin Sign \"Poisonous Moth's Scales\"",
	"Deadly Toxin \"Poisonous Moth's Dance in the Dark\"",
	"Hawk Sign \"Ill - Starred Dive\"",
	"Hawk Sign \"Ill - Starred Dive\"",
	"Hawk Sign \"Ill - Starred Dive\"",
	"Hawk Sign \"Ill - Starred Dive\"",
	"Night-Blindness \"Song of the Night Sparrow\"",
	"Night-Blindness \"Song of the Night Sparrow\"",
	"Night-Blindness \"Song of the Night Sparrow\"",
	"Night-Blindness \"Song of the Night Sparrow\"",
	"Night Sparrow \"Midnight Chorus Master\"",
	"Night Sparrow \"Midnight Chorus Master\"",
	"Night Sparrow \"Midnight Chorus Master\"",
	// stage 3 (22 cards)
	"Spiritual Birth \"First Pyramid\"",
	"Spiritual Birth \"First Pyramid\"",
	"Spiritual Birth \"First Pyramid\"",
	"Spiritual Birth \"First Pyramid\"",
	"Origin Sign \"Ephemerality 137\"",
	"Origin Sign \"Ephemerality 137\"",
	"Origin Sign \"Ephemerality 137\"",
	"Ambition Sign \"Buretsu Crisis\"",
	"Ambition Sign \"Masakado Crisis\"",
	"Ambition Sign \"Yoshimitsu Crisis\"",
	"Ambition Sign \"General Headquarters Crisis\"",
	"Land Sign \"Three Sacred Treasures - Sword\"",
	"Land Sign \"Three Sacred Treasures - Orb\"",
	"Land Sign \"Three Sacred Treasures - Mirror\"",
	"Land Scheme \"Three Sacred Treasures - Country\"",
	"Ending Sign \"Phantasmal Emperor\"",
	"Ending Sign \"Phantasmal Emperor\"",
	"Pseudo-History \"The Legend of Gensokyo\"",
	"Pseudo-History \"The Legend of Gensokyo\"",
	"Future \"Gods' Realm\"",
	"Future \"Gods' Realm\"",
	"Future \"Gods' Realm\"",
	// stage 4A (23 cards)
	"Dream Sign \"Duplex Barrier\"",
	"Dream Sign \"Duplex Barrier\"",
	"Dream Sign \"Great Duplex Barrier\"",
	"Dream Sign \"Great Duplex Barrier\"",
	"Spirit Sign \"Fantasy Seal -Spread-\"",
	"Spirit Sign \"Fantasy Seal -Spread-\"",
	"Scattered Spirit \"Fantasy Seal -Worn-\"",
	"Scattered Spirit \"Fantasy Seal -Worn-\"",
	"Dream Sign \"Evil - Sealing Circle\"",
	"Dream Sign \"Evil - Sealing Circle\"",
	"Divine Arts \"Omnidirectional Oni - Binding Circle\"",
	"Divine Arts \"Omnidirectional Oni - Binding Circle\"",
	"Spirit Sign \"Fantasy Seal -Concentrate-\"",
	"Spirit Sign \"Fantasy Seal -Concentrate-\"",
	"Migrating Spirit \"Fantasy Seal -Marred-\"",
	"Migrating Spirit \"Fantasy Seal -Marred-\"",
	"Boundary \"Duplex Danmaku Barrier\"",
	"Boundary \"Duplex Danmaku Barrier\"",
	"Great Barrier \"Hakurei Danmaku Barrier\"",
	"Great Barrier \"Hakurei Danmaku Barrier\"",
	"Divine Spirit \"Fantasy Seal -Blink-\"",
	"Divine Spirit \"Fantasy Seal -Blink-\"",
	"Divine Spirit \"Fantasy Seal -Blink-\"",
	// stage 4B (23 cards)
	"Magic Sign \"Milky Way\"",
	"Magic Sign \"Milky Way\"",
	"Magic Space \"Asteroid Belt\"",
	"Magic Space \"Asteroid Belt\"",
	"Magic Sign \"Stardust Reverie\"",
	"Magic Sign \"Stardust Reverie\"",
	"Black Magic \"Event Horizon\"",
	"Black Magic \"Event Horizon\"",
	"Love Sign \"Non - Directional Laser\"",
	"Love Sign \"Non - Directional Laser\"",
	"Love Storm \"Starlight Typhoon\"",
	"Love Storm \"Starlight Typhoon\"",
	"Love Sign \"Master Spark\"",
	"Love Sign \"Master Spark\"",
	"Loving Heart \"Double Spark\"",
	"Loving Heart \"Double Spark\"",
	"Light Sign \"Earthlight Ray\"",
	"Light Sign \"Earthlight Ray\"",
	"Light Blast \"Shoot the Moon\"",
	"Light Blast \"Shoot the Moon\"",
	"Magicannon \"Final Spark\"",
	"Magicannon \"Final Spark\"",
	"Magicannon \"Final Master Spark\"",
	// stage 5 (19 cards)
	"Wave Sign \"Red-Eyed Hypnosis (Mind Shaker)\"",
	"Wave Sign \"Red-Eyed Hypnosis (Mind Shaker)\"",
	"Illusion Wave \"Red-Eyed Hypnosis (Mind Blowing)\"",
	"Illusion Wave \"Red-Eyed Hypnosis (Mind Blowing)\"",
	"Lunatic Sign \"Hallucinogenic Tuning (Visionary Tuning)\"",
	"Lunatic Sign \"Hallucinogenic Tuning (Visionary Tuning)\"",
	"Lunatic Gaze \"Lunatic Stare Tuning (Illusion Seeker)\"",
	"Lunatic Gaze \"Lunatic Stare Tuning (Illusion Seeker)\"",
	"Loafing Sign \"Life and Spirit Stopping (Idling Wave)\"",
	"Loafing Sign \"Life and Spirit Stopping (Idling Wave)\"",
	"Indolence \"Life and Spirit Stopping (Mind Stopper)\"",
	"Indolence \"Life and Spirit Stopping (Mind Stopper)\"",
	"Spread Sign \"Moon of Truth (Invisible Full Moon)\"",
	"Spread Sign \"Moon of Truth (Invisible Full Moon)\"",
	"Spread Sign \"Moon of Truth (Invisible Full Moon)\"",
	"Spread Sign \"Moon of Truth (Invisible Full Moon)\"",
	"Lunar Eyes \"Lunar Rabbit's Remote Mesmerism (Tele-Mesmerism)\"",
	"Lunar Eyes \"Lunar Rabbit's Remote Mesmerism (Tele-Mesmerism)\"",
	"Lunar Eyes \"Lunar Rabbit's Remote Mesmerism (Tele-Mesmerism)\"",
	// stage 6A (28 cards)
	"Spacesphere \"Earth in a Pot\"",
	"Spacesphere \"Earth in a Pot\"",
	"Spacesphere \"Earth in a Pot\"",
	"Spacesphere \"Earth in a Pot\"",
	"Awakened God \"Memories of the Age of the Gods\"",
	"Awakened God \"Memories of the Age of the Gods\"",
	"God Sign \"Genealogy of the Celestials\"",
	"God Sign \"Genealogy of the Celestials\"",
	"Revival \"Seimei Yugi -Life Game- \"",
	"Revival \"Seimei Yugi -Life Game- \"",
	"Resurrection \"Rising Game\"",
	"Resurrection \"Rising Game\"",
	"Leading God \"Omoikane's Device\"",
	"Leading God \"Omoikane's Device\"",
	"Mind of God \"Omoikane's Brain\"",
	"Mind of God \"Omoikane's Brain\"",
	"Curse of the Heavens \"Apollo 13\"",
	"Curse of the Heavens \"Apollo 13\"",
	"Curse of the Heavens \"Apollo 13\"",
	"Curse of the Heavens \"Apollo 13\"",
	"Esoterica \"Astronomical Entombing\"",
	"Esoterica \"Astronomical Entombing\"",
	"Esoterica \"Astronomical Entombing\"",
	"Esoterica \"Astronomical Entombing\"",
	"Forbidden Elixir \"Hourai Elixir\"",
	"Forbidden Elixir \"Hourai Elixir\"",
	"Forbidden Elixir \"Hourai Elixir\"",
	"Forbidden Elixir \"Hourai Elixir\"",
	// stage 6B (44 cards)
	"Medicine Sign \"Galaxy in a Pot\"",
	"Medicine Sign \"Galaxy in a Pot\"",
	"Medicine Sign \"Galaxy in a Pot\"",
	"Medicine Sign \"Galaxy in a Pot\"",
	"Impossible Request \"Jewel from the Dragon's Neck -Five-Colored Shots-\"",
	"Impossible Request \"Jewel from the Dragon's Neck -Five-Colored Shots-\"",
	"Divine Treasure \"Divine Dragon Bullet\"",
	"Divine Treasure \"Divine Dragon Bullet\"",
	"Impossible Request \"Buddha's Stone Bowl -Indomitable Will-\"",
	"Impossible Request \"Buddha's Stone Bowl -Indomitable Will-\"",
	"Divine Treasure \"Buddhist Diamond\"",
	"Divine Treasure \"Buddhist Diamond\"",
	"Impossible Request \"Robe of Fire Rat -Unhurried Mind-\"",
	"Impossible Request \"Robe of Fire Rat -Unhurried Mind-\"",
	"Divine Treasure \"Salamander Shield\"",
	"Divine Treasure \"Salamander Shield\"",
	"Impossible Request \"Swallow's Cowrie Shell -Everlasting Life-\"",
	"Impossible Request \"Swallow's Cowrie Shell -Everlasting Life-\"",
	"Divine Treasure \"Life Spring Infinity\"",
	"Divine Treasure \"Life Spring Infinity\"",
	"Impossible Request \"Bullet Branch of Hourai -Rainbow Danmaku -\"",
	"Impossible Request \"Bullet Branch of Hourai -Rainbow Danmaku -\"",
	"Divine Treasure \"Jeweled Branch of Hourai -Dreamlike Paradise-\"",
	"Divine Treasure \"Jeweled Branch of Hourai -Dreamlike Paradise-\"",
	"\"End of Imperishable Night -New Moon-\"",
	"\"End of Imperishable Night -Crescent Moon-\"",
	"\"End of Imperishable Night -First Quarter's Moon-\"",
	"\"End of Imperishable Night -Matsuyoi-\"",
	"\"End of Imperishable Night -11 o'Clock-\"",
	"\"End of Imperishable Night -Half to Midnight-\"",
	"\"End of Imperishable Night -Midnight-\"",
	"\"End of Imperishable Night -Half Past Midnight-\"",
	"\"End of Imperishable Night -1 o'Clock-\"",
	"\"End of Imperishable Night -Half Past 1-\"",
	"\"End of Imperishable Night -Dead of Night-\"",
	"\"End of Imperishable Night -Half Past 2-\"",
	"\"End of Imperishable Night -3 o'Clock-\"",
	"\"End of Imperishable Night -Half Past 3-\"",
	"\"End of Imperishable Night -4 o'Clock-\"",
	"\"End of Imperishable Night -Half Past 4-\"",
	"\"End of Imperishable Night -Morning Mist-\"",
	"\"End of Imperishable Night -Dawn-\"",
	"\"End of Imperishable Night -Morning Star-\"",
	"\"End of Imperishable Night -Rising World-\"",
	// extra stage (14 cards)
	"Past \"Old History of an Untrodden Land -Old History-\"",
	"Reincarnation \"Ichijou Returning Bridge\"",
	"Future \"New History of Fantasy -Next History-\"",
	"Limiting Edict \"Curse of Tsuki-no-Iwakasa\"",
	"Undying \"Fire Bird -Feng Wing Ascension-\"",
	"Fujiwara \"Wounds of Metsuzai Temple\"",
	"Undying \"Xu Fu's Dimension\"",
	"Expiation \"Honest Man's Death\"",
	"Hollow Being \"Wu\"",
	"Inextinguishable \"Phoenix's Tail\"",
	"Hourai \"South Wind, Clear Sky -Fujiyama Volcano-\"",
	"\"Possessed by Phoenix\"",
	"\"Hourai Doll\"",
	"\"Imperishable Shooting\"",
	// last words (17 cards)
	"\"Unseasonal Butterfly Storm\"",
	"\"Blind Nightbird\"",
	"\"Emperor of the Land of the Rising Sun\"",
	"\"Stare of the Hazy Phantom Moon (Lunatic Red Eyes)\"",
	"\"Heaven Spider's Butterfly-Capturing Web\"",
	"\"Tree-Ocean of Hourai\"",
	"\"Phoenix Rebirth\"",
	"\"Ancient Duper\"",
	"\"Total Purification\"",
	"\"Fantasy Nature\"",
	"\"Blazing Star\"",
	"\"Deflation World\"",
	"\"Matsuyoi-Reflecting Satellite Slash\"",
	"\"The Phantom of the Grand Guignol\"",
	"\"Scarlet Destiny\"",
	"\"Saigyouji Parinirvana\"",
	"\"Profound Danmaku Barrier -Phantasm, Foam and Shadow-\""
};
